### ISSUE TITLE
Significant CPU spikes with Filter using more than 4 threads

### ISSUE THREAD

**Issue by W4too** [surge-synthesizer/surge-rack#1001]
I don't know if this issue is related to VCV, my system or the Surge XT plugin but i noticed that i get CPU spikes when i have to use more than 4 threads with my patches and modulating a third Filter instance. With 2 instances, nothing really moves on the max digit but with 3, it can easely jump from 50 % to 200 or 300 %.

It's less visible in my example (a very basic patch) but this gap is multiplied by the patch size wich is problematic knowing i adapt the thread number to the ressource behavior. 

I noticed the problem only with the Surge Filter but it could be related to my setup.

![4_threads](https://github.com/surge-synthesizer/surge-rack/assets/100092785/28124626-0003-4c3c-9400-30be07e2a750)

![5_threads](https://github.com/surge-synthesizer/surge-rack/assets/100092785/c8490a2d-e427-4335-9eea-20bb28545f4d)

**Comment by baconpaul** [comment]
Well its probably related to all three.

The filter uses a bunch of optimizations to run well in a single threaded environment which, i could easily imagine, deal poorly with thread migration and the like. I'm suprised it's that extreme though. 

But also I note you don't have any audio in on the filter. I wonder if that's somehow messing me up! Have you tried it with just noise-in-noise-out on the stereo channel to make sure that it is a full test?

**Comment by baconpaul** [comment]
I doubt it’s only your setup. Let me see this week if I can repro on my Mac.

i do have one thought which involves fpu flags and a bug we fixed in surge proper. If I make a nightly this week you know how to install and run thst yes? If not I’ll help out.  But won’t get to it today.

interesting. On and absent modulation no problem right? And the problem is only at high mod depths?

**Comment by W4too** [comment]
If a nightly is .vcvplugin to put in the VCV plugin folder, i know how to install it (i'm on Windows).
I didn't notice any problem without modulation but i don't know if it starts at high mod depths (more than 5v ?).
Thanks anyway.

**Comment by baconpaul** [comment]
Ok cool I have a theory but can’t get to it until Monday. Will post here with more in the week

thanks for the report

**Comment by baconpaul** [comment]
Hi. sorry GitHub auto closed this when i referred to it in a PR. So re-opened.

I couldn't reproduce this on my mac, but i had one thought and made a change to the code.

https://github.com/surge-synthesizer/surge-rack/releases/tag/Nightly

Can you let me know if you still see it with that nightly? If that fixes it then I think there's a bug in rack which I need to mail support about - I'd sooner not leave that change in the codebase - but if that's not it then i'll need to boot windows and try and repro myself there.

**Comment by W4too** [comment]
Hi
I made the test with the nightly build and got the same problem.
Hope you can reproduce it on windows.

**Comment by W4too** [comment]
Hi,
Sorry coming back with this but i was waiting the last update to check if the issue was enventualy fixed, and i'm still getting it as soon as i'm using and modulating more than 3 filters and 4 threads in VCV.

I made a test in a blank panel : 
![1](https://github.com/user-attachments/assets/e09a0e2f-46eb-4fad-b915-3c4120e0d23a)

![2](https://github.com/user-attachments/assets/904a5cb5-468c-4c4c-a525-2f622ceb388b)

**Comment by W4too** [comment]
Hi,

I've finally found this was related to my settings (a mistake made in Process Lasso).
Sorry about the inconvenience.

**Comment by baconpaul** [comment]
Oh I’m glad to hear that it’s resolved! Thank you for letting us know
