### ISSUE TITLE
modulation as unipolar not bipolar

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge-rack#1006]
HI is there a way to do this on all the modules?

**Comment by XtremeSounds** [comment]
For example on the quad lfo. The mods are only bipolar. Im sure all the rest are as well.

**Comment by baconpaul** [comment]
Yeah the quad lfo has a menu which sets uni vs bi polar

**Comment by XtremeSounds** [comment]
Ok there it is thanks

**Comment by XtremeSounds** [comment]
i wish all modulations in all modules had this feature

**Comment by baconpaul** [comment]
Which ones do not?

**Comment by XtremeSounds** [comment]
Nm I figured it out sorry. It has to do with the modulation source parameter settings not the mod knob itself.
