### ISSUE TITLE
Delay module quantize display values

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge-rack#1012]
Hi any way we can get the display to switch to values such as 1/4 1/8 dotted etc?

**Comment by Andreya-Autumn** [comment]
Hi! It should if you hook up a clock signal. Does that not work for you?

![Yes](https://github.com/user-attachments/assets/abf9f456-0dea-471e-98a4-53cc74e7be3e)

**Comment by XtremeSounds** [comment]
Thanks didn’t think of that. I guess it works.

**Comment by Andreya-Autumn** [comment]
Great, closing this then! :)
