### ISSUE TITLE
Change log out-of-date

### ISSUE THREAD

**Issue by ZwergNaseXXL** [surge-synthesizer/surge-rack#1017]
Yes, I'm a change log reader! 🤓
docs/changelog.md seems to be neglected since version 2.2.1 and we're at 2.2.4 now. I'd love to know what happened in one of my favorite plugins. Thanks!

**Comment by baconpaul** [comment]
The answer is

+ a49b8651bbc5fb8018c35e2aa9570a8ae3c4e713 Uni- and Bi-polar LFO waveforms properly align (#971)
+ 45feb9655a96d4b3fc30f6006feb0d835b18ef93 Fix two CXOR range/randomization errors (#972)
+ 4de2a04afd64b777535c5752810dfa78e986ec13 Quad LFO Independent Trigger Fix (#973)
+ d9a50c269ace38fa3f52dfbaf2a1310968dfda2c Update nightly changelog
+ afb5a569c465287e5cf122b52704ddc179e78dfc Move nightly changelog to changelog now 2.2 is out
+ 07f8c160f38cd9d5037ec1b01035a26d3adf527c Update changelog.md
+ e96ba1e9ef7cc974dabafc359ee28cfc908ddcfe Less cardinal specific changes (#974)
+ cb39088e19be8cff589b68e71d30daffd10ebda5 Allow some non-rack build configurations to proceed (#978)
+ 42faa6466fef23f7dd5b762047c5afc68e4cc237 Connector module upgrades - Same Row, RingMod fixes
+ f7037ece4be74f7796223cbdc6928d86a8112161 Prep for 2.2.2.0
+ 9c5ad894006d2d9a66da91833fcc17e1b8456845 Dyanmic Deactivation of Widgets; Use in RingMod (#981)
+ 1c5fddaf61253cdd11ac165f83326120666fa4cf Final 2.2.2 tweaks (#982)
+ 66e31c297dfa2e1c9d4f88cf24e3995d8a3dafb6 Add Detune Extend panel glyph; update to 2024 copyright (#986)
+ 560eb7f65728f964caf7d4ff27bf7512afb20bdb Update README.md
+ af33f198e7cc7ce260d0d8e16de28609c6f4942f Reset I/O buffers when we re-init effects (#990)
+ bb3cf75bafc3a72304a41790bb577c6aac4ca924 Fix uninitalized values in Waveshaper (#993)
+ 4e0c376ab1995ab7c02fc0201039be407a1d457c Do not use -fno-char8_t on non c++20 builds (#994)
+ 078c05737254b0a71cff6b5761c4dd9118648a71 Upgrade Surge; FPU Guard VCF (#1002)
+ 4241e5c822e443971e8d2732dae84418e499887e Move to latest surge submodule; C++20 (#1004)
+ 3fa61e8b5b73f8a3827d9092056b24e4376b51b4 Revert "Move to latest surge submodule; C++20 (#1004)"
+ 539cfa40c0e3c782c856d5233a7449fac1670fc3 Keep the 2.5.1 SDK constraint in github workflows
+ da8a6a975c478007bb8383d3807ec39f666d5335 update workflow actions (#1008)
+ 7550d7ef443a6e25622b511b6e22be7fbcbaff63 Fix an error with FX Mod Param Labeleing (#1013)
+ 758b9637dfb1b89fc9b79bc330df420d4a374072 Upgade to a (slightly tweaked) XT 1.3.3 submodule (#1014)
+ dde0b4af675b6f20bca38e1caa6447990a6e8db8 2.2.4.0 release branch


but I should put that in the changelog in a more human readable form. Most of those don't matter at all.

**Comment by baconpaul** [comment]
Anyway pushed that into the changelog. Thanks for the reminder.
