### ISSUE TITLE
Decay and Release Curve tooltips in EGxVCA both say 'Decay Curve'

### ISSUE THREAD

**Issue by landgrvi** [surge-synthesizer/surge-rack#1018]
As the title says. Hovering over the decay curve shows 'Decay Curve: Standard' (for example), and hovering over the release curve also shows 'Decay Curve'.

I tried submitting a PR for this - looks like a change in line 269 of EGxVCA.h - but got an error 403. Don't know if that was a problem on my end or if you're not accepting PRs from everyone, but anyway, would be happy to try again if the PR should work!

**Comment by baconpaul** [comment]
We gladly accept prs!
