### ISSUE TITLE
EGxVCA EOC output doesn't work with clock input patched

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-rack#1021]
It'll output constant 0 for EOC, constant 10 for SOC, etc etc.

**Comment by Andreya-Autumn** [comment]
Well... :)
`            if (tempoSynced)
            {
                auto av = aTS + modAssist.modvalues[EG_A][c];
                auto dv = dTS + modAssist.modvalues[EG_D][c];
                auto sv = sTS + modAssist.modvalues[EG_S][c];
                auto rv = rTS + modAssist.modvalues[EG_R][c];
                procs[c]->process(av, dv, getMode() == 0 ? modAssist.values[EG_S][c] : sv, rv, as,
                                  ds, rs, inputs[GATE_IN].getVoltage(polyGate * c) > 2);
            }
            else
            {
                auto pst = procs[c]->stage;
                procs[c]->process(modAssist.values[EG_A][c], modAssist.values[EG_D][c],
                                  modAssist.values[EG_S][c], modAssist.values[EG_R][c], as, ds, rs,
                                  inputs[GATE_IN].getVoltage(polyGate * c) > 2);
                auto nst = procs[c]->stage;

                if (pst != nst)
                {
                    if (ett == ALL_TRANSITIONS || (nst == ENVT::s_attack && ett == START_ATTACK) ||
                        (nst == ENVT::s_decay && ett == START_DECAY) ||
                        (nst == ENVT::s_sustain && !getMode() && ett == START_SUSTAIN) ||
                        (nst == ENVT::s_sustain && getMode() && ett == START_HOLD) ||
                        (nst == ENVT::s_release && ett == START_RELEASE) ||
                        (nst > ENVT::s_release && ett == EO_CYCLE))
                    {
                        eocCountdown[c] = eocInit;
                    }
                }
                else
                {
                    if (eocCountdown[c])
                        eocCountdown[c]--;
                }
            }`

**Comment by baconpaul** [comment]
Oh yeah that pst nst block needs to be in both branches

**Comment by baconpaul** [comment]
Yeah took 10 minutes.

Will update community and tag for a release also.
