### ISSUE TITLE
Unison or Osc Type changes in SurgeOSC can pop

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#118]
Unison in classic requires me to re-init which will cause a pop/click if we are mid oscillation in the prior state. No really great solution to this but pull another 5 or so blocks before I reset and blend that in with a mix I guess is the answer.

**Comment by baconpaul** [comment]
Details:

* In Surge, the oscillator type and the oscillator union count are set at the start of oscillation time and are constant
* In the SurgeOSC module, then, to deal with button bank changes (from Classic to Sine) or with unison count changes (inside the Oscillators which support unison) we re-set the oscillator
* Our blocking mechanism doesn't account for this meaning you can get a non-continuous waveform
* The solution is when you change one of these parameters pull a few of blocks out of the oscillator before you switch and then blend that in over the next few blocks, so that when you switch unison the next samples are (1-t) * oldUnison + t * newUnison for some period t (scaled accordingly).

Here's how that maps to code

* The entire codebase is in surge-rack/src/SurgeOSC.hpp (following our pattern that DSP is in the hpp and UI is in the cpp)
* At head, around line 170 is where we change the oscillator based on type with `respawn(conf.first)`
* At head, around line 211 is where we re-init when unison changes with `surge_osc->init(72.0)`
* What I would do is the following
   * Add a few new members, 
       * "inBlend, blendSteps" and then also
       * BLEND_BLOCKS=4 or so and
       * Add buffers floatSwitchBuffer[BLOCK_SIZE_OS*BLEND_BLOCKS] both Left and Right
   * In those spots when we shift run the process / pull loop on the oscillator BLEND_BLOCKS time
     and set up the state variables
   * In the output generation at line 229 (avgl=...) blend in the pulled samples if your state is set
   * Advance your stepper and turn off the blend mode at the end of the blended blocks

Something like that.

**Comment by bytecrew** [comment]
Is there an easy way to replicate the popping sound?

**Comment by baconpaul** [comment]
My guess is if you attached a modulation source to the unison control you would hear it no problem. That init will reset the phase which willl pop you sometimes.  You sorta have to play with it and mostly get lucky (since the frequency is the same the reset is exactly harmless when phases match and exactly harmful when they don't)

**Comment by baconpaul** [comment]
Oh modulation doesn't work on unison count! Well we should fix that too.

But the way I heard it was to run the oscillator in classic mode and set the unison spread high then toggle it from 2 to 3 back and forth by hand. You will hear it is a non-smooth transition. Sometimes it is a super-tight attack and sometimes there is a pop.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge-rack/issues/165 There's the issue for modulation on unison.
