### ISSUE TITLE
Surge no longer compiles with Rack v1-gpl

### ISSUE THREAD

**Issue by NielsMayer** [surge-synthesizer/surge-rack#119]
Following the compile instructions on Kubuntu 18.04.2 system, I get the following new error with "v1-gpl" Rack (v1.dev.09c8527). Previously I was able to successfully compile with "v1" branch of Rack (v1.dev.380d634). But a fresh compile of branch 'v1-gpl' results in errors: 

`make: *** [build/src/SurgeRackGUI.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
../../compile.mk:61: recipe for target 'build/src/SurgeWidgets.cpp.o' failed
make: *** [build/src/SurgeWidgets.cpp.o] Error 1
../../compile.mk:61: recipe for target 'build/src/SurgeVCF.cpp.o' failed
make: *** [build/src/SurgeVCF.cpp.o] Error 1
../../compile.mk:61: recipe for target 'build/src/SurgeWaveShaper.cpp.o' failed
make: *** [build/src/SurgeWaveShaper.cpp.o] Error 1
../../compile.mk:61: recipe for target 'build/src/SurgeVOC.cpp.o' failed
make: *** [build/src/SurgeVOC.cpp.o] Error 1
../../compile.mk:61: recipe for target 'build/src/SurgeWTOSC.cpp.o' failed
make: *** [build/src/SurgeWTOSC.cpp.o] Error 1
../../compile.mk:61: recipe for target 'build/src/SurgeOSC.cpp.o' failed
make: *** [build/src/SurgeOSC.cpp.o] Error 1
In file included from ../../include/common.hpp:2:0,
                 from ../../include/rack.hpp:4,
                 from src/UserInteractionsRack.cpp:2:
src/UserInteractionsRack.cpp: In function ‘void Surge::UserInteractions::promptError(const string&, const string&, SurgeGUIEditor*)’:
../../include/logger.hpp:14:27: error: ‘logger’ has not been declared
 #define WARN(format, ...) logger::log(rack::logger::WARN_LEVEL, __FILE__, __LINE__, format, ##__VA_ARGS__)
                           ^
src/UserInteractionsRack.cpp:18:5: note: in expansion of macro ‘WARN’
     WARN(oss.str().c_str());
     ^~~~
src/UserInteractionsRack.cpp: In function ‘Surge::UserInteractions::MessageResult Surge::UserInteractions::promptOKCancel(const string&, const string&, SurgeGUIEditor*)’:
../../include/logger.hpp:13:27: error: ‘logger’ has not been declared
 #define INFO(format, ...) logger::log(rack::logger::INFO_LEVEL, __FILE__, __LINE__, format, ##__VA_ARGS__)
                           ^
src/UserInteractionsRack.cpp:38:5: note: in expansion of macro ‘INFO’
     INFO(oss.str().c_str());
     ^~~~
../../compile.mk:61: recipe for target 'build/src/UserInteractionsRack.cpp.o' failed
make: *** [build/src/UserInteractionsRack.cpp.o] Error 1
`

**Comment by NielsMayer** [comment]
Note that I moved the old compiled "v1" plugin into the "v1-gpl" plugin directory and it worked.

**Comment by baconpaul** [comment]
Oh sorry I haven't done a pull on V1 in a few days. Let me do that now and fx it up.

**Comment by baconpaul** [comment]
OK if you pull master it will build again. Thanks!
