### ISSUE TITLE
Report on osc switch inconsistency 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#145]
From ODdy

I find that if you jump to Noise from FM2 or FM3 it won't give the correct setting

but if you jump from Sine or Classic it comes up proper

**Comment by baconpaul** [comment]
![OddyOSC](https://user-images.githubusercontent.com/13387561/57983338-9772c700-7a1e-11e9-8e27-828623f3fd92.gif)

Hey @tank-trax I can't reproduce this. Here's a gif. Can you give some more information? Thanks!

**Comment by tank-trax** [comment]
![surge osc 02](https://user-images.githubusercontent.com/41337033/57986490-986a1f80-7a43-11e9-898c-d07a4a60c90b.gif)

**Comment by tank-trax** [comment]
most recent build looks more stable

**Comment by tank-trax** [comment]
all presets load on Init except for Noise

![osc nonoise 01](https://user-images.githubusercontent.com/41337033/57986790-54791980-7a47-11e9-9cbc-95eda16558c4.gif)

once loaded as a preset the changes between FM3 and Noise no longer give the same anomoly

![fm32noiseok](https://user-images.githubusercontent.com/41337033/57986799-7377ab80-7a47-11e9-9a96-29f0fe29c8f9.gif)

as an example, changes can be made to FM3 and moving back and forth will remember each buttons previous setting

![fm32noiseok 01](https://user-images.githubusercontent.com/41337033/57986885-6f985900-7a48-11e9-8753-422d351b2101.gif)

**Comment by baconpaul** [comment]
OK I think this is a problem with parameters of type "none" not acting properly with the knob cache. I know @bytecrew is in this code now so I'll leave it sit but if I had to guess it would be the knobSaver not dealing properly with none-type controls (of which noise has a lot as does sine).

And we do need to restream those presets...
