### ISSUE TITLE
Plugin will not load on Windows

### ISSUE THREAD

**Issue by caecos** [surge-synthesizer/surge-rack#151]
[28.077 warn src/plugin.cpp:84] Failed to load library ./plugins/SurgeRack/plugin.dll: code 1114

**Comment by caecos** [comment]
Forgot to add with Rack 0.6.2c

**Comment by baconpaul** [comment]
Thanks! We are (literally right now) about to remove 0.6.2 support and move to 1.0 only. But I will fire up a VM and test 1.0 on windows this week. We build windows but we only run mac and linux right now.

**Comment by baconpaul** [comment]
Hi OK so I just did the 1.0 build as part of my testing on windows and yup, the DLL doesn't load. Error "1114" is the helpful "dll did not initialize"

So no idea here. Have to debug this one day soon!

It works in linux and mac if that helps?

**Comment by baconpaul** [comment]
I spent a bit of time on this. On windows the symbol export isn't working properly. I do not know why.

I asked over at the rack community

https://community.vcvrack.com/t/windows-linking-help/3453

**Comment by baconpaul** [comment]
I have a fix to this. Will push it in next half hour.

**Comment by baconpaul** [comment]
OK if you rebuild head with v1.0 it loads fine on windows as well as mac and linux. Thanks for flagging!

**Comment by caecos** [comment]
Thank’s for taking the time to respond…

Marc

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Paul <notifications@github.com>
Envoyé : Sunday, May 19, 2019 1:49:58 PM
À : surge-synthesizer/surge-rack
Cc : caecos; Author
Objet : Re: [surge-synthesizer/surge-rack] Plugin will not load on Windows (#151)


OK if you rebuild head with v1.0 it loads fine on windows as well as mac and linux. Thanks for flagging!
