### ISSUE TITLE
Fractions not showing when BPM displayed (Linux)

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge-rack#175]
In the panels that show the seconds or beats per minute, when temposync is enabled it does not display the beats per bar before the @ symbol

![fractions missing bpm 01](https://user-images.githubusercontent.com/41337033/58360934-64369a80-7e59-11e9-9ed7-8c66f3c59387.png)

[rack.surge.drone.pulse.01.vcv.zip](https://github.com/surge-synthesizer/surge-rack/files/3218852/rack.surge.drone.pulse.01.vcv.zip)

**Comment by baconpaul** [comment]
Thanks! I’ll take a look later this weekend I hope - maybe early next week.

**Comment by tank-trax** [comment]
the smaller orange knobs work, only that the values or changes to them are not displaying

**Comment by baconpaul** [comment]
OK cool just confirmed it does show for me macOS so I bet I am not initializing something somewhere. Thanks will take a look!

**Comment by baconpaul** [comment]
Yeah and confirmed it doesn't show up in linux. Thanks. Great bug report! I'm sure I can find it this weekend.

**Comment by baconpaul** [comment]
Fixed!
