### ISSUE TITLE
Rack v1: compilation fails on Windows in mingw ubuntu cross compile

### ISSUE THREAD

**Issue by cschol** [surge-synthesizer/surge-rack#218]
Compilation fails on Windows cross-compilation on Ubuntu Linux 18.04:

```
surge/src/common/SurgeStorage.cpp:26:10: fatal error: Shellapi.h: No such file or directory
 #include <Shellapi.h>
          ^~~~~~~~~~~~
compilation terminated.
/home/cschol/src/Rack-1.0/dist/Rack-SDK/compile.mk:61: recipe for target 'build/surge/src/common/SurgeStorage.cpp.o' failed
```

**Comment by baconpaul** [comment]
It builds perfectly on windows though. How do I replicate your environment?

**Comment by cschol** [comment]
Found the issue: I am cross-compiling with `mingw32` on Ubuntu 18.04. This is something that the Plugin Manager build system also **might** do, so it should be supported.

```
diff --git a/src/common/SurgeStorage.cpp b/src/common/SurgeStorage.cpp
index c600bd4..2cf99da 100644
--- a/src/common/SurgeStorage.cpp
+++ b/src/common/SurgeStorage.cpp
@@ -23,8 +23,8 @@
 #include "ConfigurationXml.h"
 #else
 #include <windows.h>
-#include <Shellapi.h>
-#include <Shlobj.h>
+#include <shellapi.h>
+#include <shlobj.h>
 #endif
 
 #include <sstream>
```

When cross-compiling, it apparently does not like the capitalized header includes. Does it work on Windows with the lower-case versions?

**Comment by baconpaul** [comment]
Oh cool I can check that easily tomorrow. It should. Thank you for the fix! I will apply it and update this and the library issue both.

**Comment by cschol** [comment]
Perfect. Thank you!

**Comment by baconpaul** [comment]
Oh just checking did you make -k? We’re there any others? Thanks!

**Comment by cschol** [comment]
No others. With those changes it cross-compiles for Windows.

**Comment by baconpaul** [comment]
Great - away from computer for a bit but I can get this before end of tomorrow no problem

Thanks!

**Comment by baconpaul** [comment]
This change is now in both master and release/1.beta1.0 branches 

Thank you very much!
