### ISSUE TITLE
Multithreaded preset scan crashes at startup

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#229]
Community user Pgatt reported that in a multithreaded mac startup SurgeRotary would crash sometimes in preset scanning; and removing the res/presets directory resolved it. So clearly review this code since Rack is doing something with threads I don’t expect.

**Comment by pgatt** [comment]
It's now doing it again - even without the presets folder present...

**Comment by baconpaul** [comment]
Hmm OK well I’m back online in a week with my laptop. I will look then!

**Comment by baconpaul** [comment]
Also: Do you have a stack or log you could attach here with the new crash? Thank you!

**Comment by pgatt** [comment]
Actually it might have been my bad - I think I may have clicked update to the plugin manager beta again accidentally. Will let you know if it happens again.

**Comment by baconpaul** [comment]
OK thanks! I’ll definitely fix the underlying problem when I’m back from vacation though. Appreciate it!

**Comment by baconpaul** [comment]
While I can't reliably repo this, the mac implementation we stubbed in of filesystem where you get the crash is not re-entrant so I will fix that in the submodule in the next couple of days.

**Comment by baconpaul** [comment]
@pgatt I just pushed a fix for this. The nightly build should have it in place in about 10 minutes if you would like to download and try. I'll get this fix and a few others together for the plugin manager this week.
