### ISSUE TITLE
Param initialization vs surge Initialization (FX) 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#230]
Community user pgatt reports 

> The initialize problem is this: when you bring Rotary into your rack - it has settings of 25% and 50% for Doppler and Amp Mod. When you initialize by either double clicking the individual dials or right-click on the module and select initialize (or press Command I) the dials are both set to 0%. Not a big deal but not how modules are expected to work.

That’s because fox config param are all 0-1 at 0 and I don’t out the getf01 default back on the param

**Comment by Miserlou** [comment]
I also find this slightly annoying!

**Comment by baconpaul** [comment]
Yeah sorry! There’s a (good) reason it does it (from a code perspective) but I know how to fix it. I’ll have it patched up in July and get another release together. Will update this issue when it’s solved.

**Comment by baconpaul** [comment]
I just pushed a fix to this (for all the FX; not for the oscillators which have the same problem)

https://github.com/surge-synthesizer/surge-rack/releases

should have it in about 5 minutes.

**Comment by baconpaul** [comment]
Oh and tagging @pgatt here also
