### ISSUE TITLE
1.beta1.4bfb9e2 in latest Rack brings up assertion

### ISSUE THREAD

**Issue by SteveRussell33** [surge-synthesizer/surge-rack#237]
![surge](https://user-images.githubusercontent.com/41975381/60832358-9acf3700-a1b3-11e9-8004-f563105c2150.png)

Selecting ignore brings up the modules as normal.
Something your end or Rack's?

**Comment by baconpaul** [comment]
Yeah that’s my end. Same as #231 #232 #233 and #234!

I’ve been on a 2.5 week dev break otherwise it would be fixed. My guess is I have this fix together and in the nightlies on weds or so and I will close this issue then


Thanks for the accurate bug report!

**Comment by baconpaul** [comment]
Hi

I just pushed a fix for your EQ3 issues. If you go to the releases https://github.com/surge-synthesizer/surge-rack/releases you can download the zip for your platform. I have a few other changes to make but will do them in next few days and get an update in the plugin manager then.

Thanks
