### ISSUE TITLE
Surge Rotary overloads audio when synced to clock

### ISSUE THREAD

**Issue by fractalgee** [surge-synthesizer/surge-rack#249]
When adding the Rotary and plug in a clock and set the little switch to sync with clock within a second all sound stops with the audio out being completely slammed fully open. Nothing short of restarting Rack (if I remembered to turn the switch back off) to get sound back. If switch still on when restarted immediately same issue. It works fine all other ways but no way to sync it to a clock.......

**Comment by baconpaul** [comment]
Thank you

Just checking - Did you plug in a clock CV or a clock pulse/gate? The clock controls in rack require a BPM CV signal not an open/close push.

**Comment by fractalgee** [comment]
Clock plugged  (The Clock from Klirrfactory) first left hand clock out at
top of matrix

**Comment by baconpaul** [comment]
OK thanks; I don't have that module. What is the value you are sending to the clock when you get the overload? Can you drop it into a scope and send a screenshot?

I'm looking at the code. I think I will - in the next release - reliable "clk cv" to "bpm cv" everywhere to avoid confusion. I think if you send a slowly oscillating 0v / 10v as a gate into the bpm cv it may overload.

But if you are just sending a reasonable value like "a constant value of 2.3 to mean 140bpm" (or whatever) it shouldn't hang. Can you reproduce the effect with one of the free clocks in the rack ecosystem?

Thanks so much!

**Comment by fractalgee** [comment]
it was a 142bpm clock, nothing weird, as soon as one switches to 'sync to
clock' via the little switch at top audio goes bonkers. No matter which
clock or LFO used. Only way to get sound back is to delete the thing, and
restart Rack. No, scope out, just an orange signal going to the audio
module (that means audio overload)  Let me see if I can get you a scope
screen, as I am reliably able to repo this here....

**Comment by baconpaul** [comment]
Yeah OK so I can reproduce it if I use the wrong "sort" of clock.

Basically I have mislabeled the input as "clock" and should label it as "bpm". If you want a 142bpm you need to put in a constant cv signal of 2.3 or what not

If I put in a signal which oscillates 0<>10 over and over 142 times a minute, the rotary does indeed go into oblivion. I need to figure that out, obviously.

But if I put in a signal where 2^x = 142 then it works as expected.

Surge actually ships with a micro-clock with both types of outputs. If I configure this way:

<img width="737" alt="Screen Shot 2019-08-24 at 10 13 09 AM" src="https://user-images.githubusercontent.com/13387561/63638551-d3d64480-c657-11e9-9f82-f66210cfeeb3.png">

everything works. If however I configure putting the gate output in

it goes to never-never land and never comes back.

So clearly I should fix that, but right now, there's a fix in your network which I think will do what you want.

Do you see the same?

**Comment by fractalgee** [comment]
aha, figured it out, wasn't the clock in, but rather stupidly patched the
clock into the Clk CV in. That will reliably make it go bonkers as soon as
the little switch is thrown at least here. So not a major thing, but maybe
some protection against too much virtual voltage by capping it would be
good.....

So we are good for now, just something to put on list of not so urgent
things to fix as it was simple tupidity on my part, which found this bug ;)
Do with it as you feel proper...

**Comment by fractalgee** [comment]
oh and gems your modules are! thanks!!!!

**Comment by baconpaul** [comment]
Ha great yes! Absolutely I will protect against that. We are getting ready (in the VST proper) for a pretty big release end of september and I’ll rev the rack modules in line with that. I’ll make sure both a fix to the label (bpm cv rather thank clk cv) and protection (don’t set the bpm to 103232bpm) are in place with that update.

And glad you like the modules!

**Comment by fractalgee** [comment]
That rotary I have wished for since seeing Phil Lesh and the Grateful Dead
on may occasions. He had his bass going through one and sounded so cool.....

**Comment by baconpaul** [comment]
Well I gotta say I thought the intersection of digital synth, github, euro rack, and the dead left us with an almost empty set! But yeah that rotary sound is really useful - glad you like it and I’ll definitely add constraints and update this issue for the next release. Have fun!

**Comment by baconpaul** [comment]
While not closed, I am getting ready for another release and I changed the label to "bpm cv" rather than "clk cv" in the UI as a first step.

**Comment by baconpaul** [comment]
And I just dropped a clamp in also which should solve this in the upcoming release

**Comment by fractalgee** [comment]
cool, thanks, that should do the trick :)
