### ISSUE TITLE
Biquad overloads with CV control to Freq 

### ISSUE THREAD

**Issue by Petervos2018** [surge-synthesizer/surge-rack#250]
When using CV to control the freq of the Surge-Biquad the output results in an overload (NAN)
as seen on this picture : 

![SurgeBiquadOL](https://user-images.githubusercontent.com/46076474/64951133-6c3d9e80-d87d-11e9-9b97-ee62590d49e5.jpg)
Love your modules,
Greetings Peter.

**Comment by baconpaul** [comment]
Oh thanks!

We are wrapping up the 1.6.2 release of the VST/AU/LV2 version of the plugin and I’ll rev the rack plugins shortly after that. I’ll make sure to fix this. I’m 100% unsurprised you can push the biquad unstable with a bad CV input - I’ll add some bounds checking.

Thank you!

**Comment by baconpaul** [comment]
Just letting you know it took a while but I didn't forget this. We are going to have a new surge-rack release soon and the nan check is getting swept into that, so I'll close this issue once the check is in master.

Thanks!
