### ISSUE TITLE
Request: Surge Rack Parameters Mod Surge Rack Parameters..

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge-rack#27]
Considering the posibility that Surge Rack parameters could modulate inputs to Other Surge Rack parameters.. 

![surge2surgemod](https://user-images.githubusercontent.com/1504019/56937862-49b31f00-6b42-11e9-95dd-e9f58a4af310.jpg)

would this require each paramater to also output CV?

**Comment by baconpaul** [comment]
Short version: yes it would. Ports are one directional in rack (in or out)

**Comment by sense-amr** [comment]
yes so .. how about the switch switching between surge 2 surge mod or surge to external rack object "cv" mod?

**Comment by baconpaul** [comment]
@sense-amr I'm going to close this issue; in 1.0 there's no real way to do it other than to have 2 ports per position which is overkill; you can use one of the utility classes to have the same signal go two places which is what I'd end up doing here. Not that I don't like the idea, just that it's not really rack doable right now.
