### ISSUE TITLE
Feature request: Make OSC types controllable

### ISSUE THREAD

**Issue by spectromas** [surge-synthesizer/surge-rack#277]
Sorry if this is a duplicate, I did search but the relevant terms are pretty vague. 

I love the fact that the OSC module remembers the parameter positions across the different types so it would make sense to me that you should be able to automate the osc type with cv, and perhaps a slewed blend between them when changing with adjustable slew time. I'm not sure how this could be implemented, or where it could go on the UI, or if there is scope for features beyond the archetype vst synth, but I think it would be my fantasy feature for the module.

**Comment by baconpaul** [comment]
Interesting and thanks for the idea. We’re all ears for good ideas over here of course!

So the racky way I would do this is just have 2 oscillators and blend them with a mixer and control the mixer with cv. Your feature request basically amounts to doing that “inside” the module it seems.  Is there something which the internal switch would do that this wouldn’t? (The internal switch is still not a bad idea I just want to make sure I understand the use case)

From a code perspective it’s a bit ugly to do this alas - essentially I would always be running 2 oscillators so I could blend and have to index and suppress at the right spot. So want to make sure I understand properly the ideas

And glad you like the modules!

**Comment by spectromas** [comment]
Oh I love the modules, especially as they are easier on the eye now ;) 

Yes, the 'inside' method is what I'm thinking and I didn't have anything in mind that couldn't be done 'outside' really. I had in mind something like Rainbow where you can slew between scales/notes, except this would be between the osc types.

I thought that because the parameters are saved between types then it might not be a major change to have the crossfade but I can see that it's not ideal to double the load, especially for something that isn't an obvious or primary feature. 

Would it not require 3 oscillators to be running? How would you know if the cv would switch left or right if it were only 2? 

Or maybe an expander module would be a better way to go? Then (I presume) you could carry on with one at a time in the main module but have all types outputting from the expander if it is next to it/connected so that it can be modulated externally.

**Comment by baconpaul** [comment]
Right
So surge proper has 3 oscillators, fm routing between them, 2 digital ring mods and a noise channel. I’ve thought about a mixer block module which does something like that but haven’t spent time coding it. Something like “3 oscillators with 6 levels (1,2,3,3>2fm,2>1fm,2x1,3x2) as a standalone module. That would do exactly what you want and also start unlocking some fm capabilities which haven’t really made it into rack.

Thoughts?

Will ponder

**Comment by baconpaul** [comment]
Oh and using the expander architecture is a very good idea. Then that magic mixer can just get oscillators stacked next to it.
