### ISSUE TITLE
BiQuad filter: nAn overload

### ISSUE THREAD

**Issue by Eurikon** [surge-synthesizer/surge-rack#278]
Hi Paul,
when using the BiQuad filter and selecting the BP filter.
I got an overload coming out of the module that crashed the rest of the patch.
Measuring the output with Volt Meter says: occasionally nAn

![surge-biquad-crash_bp](https://user-images.githubusercontent.com/40998416/68391276-856d1800-0167-11ea-9cca-a69d79890ca9.png)

I don't know if you been following a certain bug within Rack that has been causing crashes in patches with modules that use this string: random::normal()
It might be related this (or not).

The bug was addressed in Rack 1.1.6

**Comment by baconpaul** [comment]
Huh just making sure you are using the absolute latest code? I put a change into the BiQuad which surpasses output nans https://github.com/surge-synthesizer/surge-rack/commit/c9ddb867ae331f3ed0ad53e1cce62b387b97d3dd so I don't quite see how a nan could emerge.

Is it possible you could share your network though so I can test it?

I don't use "random::normal" - surge has its own RNGs. But appreciate the tip!

**Comment by Eurikon** [comment]
Hi Paul, i use the latest build that was delivered through the PM. 
Sure here is the patch simplified, just patch it up like this and select BP 
(or several of the other filter modes) while running. 
The envelope coming from the Spank module must be connected to the filter cut off CV input (this is key).

![surge-biquad-crash_bp](https://user-images.githubusercontent.com/40998416/68398789-97ee4e00-0175-11ea-8669-e6a4b2ea9c3a.png)

**Comment by baconpaul** [comment]
Ok thanks! I’ll take a look this weekend. Appreciate the report!

**Comment by baconpaul** [comment]
So I spent a bit of time looking and couldn't make it NaN with the 1.beta1.2 codebase but I can make it do some nasty clicks and pops.

Here's the network I'm using for testing. Do you see anything particular I'm missing from yours?

<img width="1476" alt="Screen Shot 2019-11-07 at 12 18 13 PM" src="https://user-images.githubusercontent.com/13387561/68411593-b5f98580-0158-11ea-950c-d31ae343ef85.png">

**Comment by Eurikon** [comment]
I was gonna suggest for you to try it at 48khz, but then i tried it 44khz myself, and was able to nAn crash it again.

![surge-biquad-crash_bp](https://user-images.githubusercontent.com/40998416/68424301-fa5e4300-01a3-11ea-94d0-03d7614c9935.png)

**Comment by Eurikon** [comment]
And yeah there different crashes i get here too, some with noise, some with click pop, all resulting in a dead patch. 
But especially the BP filter goes nAn

**Comment by baconpaul** [comment]
Am I misreading that patch? Looks like the voltmeter is hooked up to spank not to the filter when you see the nAn.

**Comment by Eurikon** [comment]
in all cases including the picture in last comment, the reading is after the biquad filter goes dead

![surge-biquad-crash_bp](https://user-images.githubusercontent.com/40998416/68428249-1239c500-01ac-11ea-8ef4-e021c7df224f.png)

![surge-biquad-crash_bp2](https://user-images.githubusercontent.com/40998416/68428258-16fe7900-01ac-11ea-9b32-4d89ff3e54bc.png)

**Comment by baconpaul** [comment]
Yeah cool makes sense. I’ll add some more defenses - thanks for your patience

**Comment by Eurikon** [comment]
no problemo, glad to help!

**Comment by baconpaul** [comment]
Oh and you're on windows?

**Comment by Eurikon** [comment]
yes windows 10

**Comment by Petervos2018** [comment]
Sorry to meddle, but did you try the latest version here : https://github.com/surge-synthesizer/surge-rack/releases/tag/Nightly

I ask because I had the same problem #275  And the nightly solved my issue. And it was released before you posted your issue.

Greetings Peter

**Comment by Eurikon** [comment]
Haven't tried with the nightly build yet, i use the version that was spread through the PM.
You can try testing this yourself with the nightly build you have installed, by patching it up like in the last picture above, and let us know your findings please.

**Comment by Petervos2018** [comment]
Nightly plays like a charm , yes please also test this build because I think Paul already solved it.

**Comment by baconpaul** [comment]
Yeah but the thing is: that nightly fix should also be in the 1.beta1.2 release I did on the plugin manager. But it seems it isn't somehow. The version I just ran from head didn't inf out and the version from the 1.beta1.2 did so I need to figure out what's missing.

**Comment by baconpaul** [comment]
Ahh and now I see (wow I'm glad I put the GitHub revision in my startup log message for these). The nan check is there but the frequency clamp is not. Also apparently -inf and std::is_infinite don't quite get along. Let me do a patch then if you don't mind you can both try the new nightly which results, and if that works, then I'll go ahead and do a release to the PM.

**Comment by Petervos2018** [comment]
>but the frequency clamp is not.

You are correct you made that just for me (I like to think) ;)

**Comment by baconpaul** [comment]
Yeah I just added a bunch more defensive stuff too  - let me push it now.

These biquads are really low level - Surge has a much more advanced filter architecture I want to expose. But they shouldn't nan out for sure! And they do now in some cases.

**Comment by baconpaul** [comment]
OK I just pushed an even more defensive clamp.

@Eurikon with your network and 1.beta1.2 I can get an inf and with master I can't. Can you try the nightly which just built and if it works for you I'll shuffle it into a 1.beta1.3 release in the PM?

Thanks!

**Comment by Eurikon** [comment]
Hi Paul & Peter.
I just tried out the nightly build, and can confirm that i can not reproduce the nAn crash! :) 
Thanks!!

**Comment by baconpaul** [comment]
OK just submitted this diff for a 1.beta1.3 version in the plugin manager. Will close this issue when it ships. Thanks!

**Comment by baconpaul** [comment]
This is in the PM now, so closing!
