### ISSUE TITLE
Bad skin location in resources file recovers ungracefully

### ISSUE THREAD

**Issue by pizzathehut893** [surge-synthesizer/surge-rack#287]
Hello,
After I had to reinstall Rack to a new computer, the surge for rack plugins all show up as solid red, was wondering if anyone else had this issue or a possible solution in mind.  Tried deleting and reinstalling the surge plugins, but they're still the same.  
![Screenshot (5)](https://user-images.githubusercontent.com/62157418/78183903-4305e980-742e-11ea-9e14-ad7f4df2e4f6.png)
![Screenshot (1)](https://user-images.githubusercontent.com/62157418/78183920-4b5e2480-742e-11ea-9d7a-f0ee3e89dfe4.png)

**Comment by baconpaul** [comment]
Hi @pizzathehut893 

They will show up as all red if they can’t find any of the style sheets. How did you install the plugins? Did you use the plugin manager or something else?

Can you look in your vcv rack log and see if there are any messages from SurgeRack?

**Comment by baconpaul** [comment]
Oh also just thinking. If your rack installation location changed your patch or defaults may have the wrong location of the skin files saved somewhere. Try and right mouse on one of the plugins and if you see a non-red popup menu (you should) try and go “skins/Miami” or “skins/New York” - try a couple and see if it comes back. May be I store the preference in a non-machine-portable way (if that is the case I can add an error state and fix it but the above should fix your immediate problem)

**Comment by pizzathehut893** [comment]
Hey baconpaul, thanks  for the response.  Switching the skins got them to load both in the plugin browser and in use!  Thanks so much for your help!

**Comment by baconpaul** [comment]
Great. I updated the topic to reflect the problem and will fix it in an upcoming release. Thank you, and glad you are up and running again.
