### ISSUE TITLE
Negative DC Offset from Chorus

### ISSUE THREAD

**Issue by calslate** [surge-synthesizer/surge-rack#288]
![image](https://user-images.githubusercontent.com/35624360/80716134-3341f980-8aef-11ea-845c-25375eb9a2b0.png)
As seen in the above screenshot, Chorus module is producing a negative DC offset, which causes weird clipping. It is not present when nothing is plugged into the inputs. The same happens with a polyphonic input.

**Comment by baconpaul** [comment]
So this is not so much chorus adding a negative offset as it is chorus doing the expected thing on a super-low-frequency asymmetric input. if you switch your input to sin for instance you will see the chorus being symmetric, or if you use something much closer to audio rate signal.

think of it like this: On a constant input the chorus will output zero. Your input waveform becomes near constant at the peaks and swings up. You can actually see the chorus oscillating around it.

So I don't think this is a bug. I think this is just what the chorus will do on a super low frequency input which is asymmetric the way the rack saw is.

![Screen Shot 2020-04-30 at 9 43 14 AM](https://user-images.githubusercontent.com/13387561/80717679-20b3ca00-8ac7-11ea-8054-9284eb1ae639.png)

**Comment by calslate** [comment]
Thanks. This is good to know.
