### ISSUE TITLE
Are these your debugging messages in the log?

### ISSUE THREAD

**Issue by squinkylabs** [surge-synthesizer/surge-rack#294]
I see this when my dev build of rack starts up:
```bash
[0.063 info src/Surge.cpp:23] [SurgeRack] init new
[0.063 info src/Surge.cpp:43] 0 / 14 = 0
[0.063 info src/Surge.cpp:43] 1 / 14 = 96323680
```
Is that some debugging that got left in by mistake?

**Comment by baconpaul** [comment]
Looks like it yeah! I’m gonna do a 171 soon and will clean up then - thank you!!

**Comment by squinkylabs** [comment]
sure thing!

**Comment by baconpaul** [comment]
Merging this fix. Closing issue.
