### ISSUE TITLE
WTOSC 1.7.1.1 on Rack 1.1.6 (Win) comes up initialized when loading patch

### ISSUE THREAD

**Issue by fractalgee** [surge-synthesizer/surge-rack#301]
Looks like the WTOSC does NOT save it's parameters with the VCV patch file or internally. Every time I load a patch with WTOSC in it, it comes up freshly initialized, not how it was set, so I have to remember what I had the thing set to and reset it every time. Not good, needs fixing, as that OSC is very cool, but not really usable other than for something I don't care about what happens to it afterwards....

Rack 1.1.6
Surge for Rack 1.7.1.1
Windows 10 latest patches

**Comment by baconpaul** [comment]
Oooh wow I will look today thanks

**Comment by baconpaul** [comment]
So @fractalgee is it possible for you to share some of your patches?

What I see right now is

1. In WaveTable mode the WTOSC does save
2. In Window mode it does not

The second is obviously a bug and I'll look at it but it seems you were not getting it saving in Wavetable mode either?

Thanks!

**Comment by fractalgee** [comment]
Winbdow mode is the one I am using, here is one patch (but it is all knobs
back to 0 as you know)

Wavetable mode I haven't tested yet....

**Comment by baconpaul** [comment]
Gotcha. Right so yeah window mode is definitely broken.

Thanks for the report. I'll figure it out!

**Comment by baconpaul** [comment]
Notes to self in case I don't get it in the next 20 minutes

1. This is all because the first respawn from json resets to window so we clobber when we "switch modes"
2. Duplicate in window mode does it too
3. The pc.changed on WT or Window is where we need to respond to the firstRespawn

**Comment by baconpaul** [comment]
@fractalgee I have a fix for this which is built at https://github.com/surge-synthesizer/surge-rack/releases/tag/Nightly

Can you test that build and if it works I can package up a 1.7.1.2 for the library

**Comment by fractalgee** [comment]
yep, that seems to have fixed it! Thanks a bunch (nice thing to wake up
to!) see also some other fixes which is nice, as the Rotary is now much
better than it was ! Good stuff, again, thanks for the awesome modules

**Comment by baconpaul** [comment]
Ok cool will shuffle it to the library sometime today. Thank

**Comment by baconpaul** [comment]
Submitted to the library. 1.7.1.2 should be there once the rack machinery runs - usually takes a couple of days.

Will close this issue. Thanks for the report.

**Comment by baconpaul** [comment]
FYI this hit the library manager today. Thanks.

**Comment by fractalgee** [comment]
all good, I renamed version of the beta so no red dot, so all good. works
like a charm now
