### ISSUE TITLE
Surge Flanger: Right-click on "Combs Count" dial does nothing.

### ISSUE THREAD

**Issue by Amy-Triptyline** [surge-synthesizer/surge-rack#304]
Right-click on the "Combs Count" dial does nothing. 
Rack 1.1.6. 
Macbook Pro Late 2011 
High Sierra 10.13.6 
A truly outstanding Flanger by the way, the best there is in Rack.

**Comment by baconpaul** [comment]
I’m glad you like the flanger!

it has been a while since we updated the surge rack plugins. Does the knob work to change comb count and it is just the RMB gesture?

**Comment by Amy-Triptyline** [comment]
Yes exactly that, sorry I should have mentioned that shouldn't I. So the dial functions perfectly, it's only upon right-clicking and entering an amount on it does it then appear to be unresponsive as the current comb count remains as it was. Thanks for your reply and even more thanks for such a fantastic flanger module....nothing compares. ;)

**Comment by baconpaul** [comment]
Hi!

This is fixed in surge-upstream at https://github.com/surge-synthesizer/surge/pull/6416 so when we re-release surge rack with the xt backend later this fall this problem will be solved. So I'm going to close this issue. Appreciate the report.
