### ISSUE TITLE
v2:  Surge OSC buttons are not working

### ISSUE THREAD

**Issue by jpnielsen** [surge-synthesizer/surge-rack#305]
The buttons (in Surge OSC) don't do anything.

running surge-rack v2 pre-release on Rack 2 04a9ce0

![image](https://user-images.githubusercontent.com/27916597/137152892-d22619aa-fcd6-467b-9b65-8f8f8aa20519.png)

**Comment by baconpaul** [comment]
You built the v2 branch?

**Comment by jpnielsen** [comment]
Yes,

***@***.*** MINGW64 ~/projects/Rack2/Rack/plugins/surge-rack
$ git log
commit efbd3f05b63bce8f85eeb8bc5b7c14b274f21f22 (HEAD -> v2, origin/v2)
Author: Paul Walker ***@***.***>
Date:   Thu Oct 7 09:03:43 2021 -0400

    Port to V2
