### ISSUE TITLE
VCV Rack VST version serious GUI issues in Surge modules

### ISSUE THREAD

**Issue by vcvrackideas** [surge-synthesizer/surge-rack#310]
Hi, just saw things like that and I think the main issue in zooming in VST version
![2021-12-29_10-17-25](https://user-images.githubusercontent.com/42435368/147636689-4354a620-e93a-4439-a331-05ec54a2e828.png)
![2021-12-29_09-58-57](https://user-images.githubusercontent.com/42435368/147636698-a289bd43-a290-4a06-b36c-34a02d4cce65.png)

**Comment by baconpaul** [comment]
Can you attach the rack log?
Looks like ttf resource load is failing
I don’t have a working rack dev environment now so resolution will be slow
Appreciate the report. Thanks!
