### ISSUE TITLE
Surge for rack skin issue

### ISSUE THREAD

**Issue by lancevans** [surge-synthesizer/surge-rack#313]
I have a problem with surge. Skins not loading and not showing up in the list. Can’t find files. although they are in the folder.
![Surge for rack](https://user-images.githubusercontent.com/99194708/152809411-ce3b56a4-9e97-46ab-9c1e-2435745f872c.jpg)
![Surge for rack2](https://user-images.githubusercontent.com/99194708/152809459-ae82d05d-cccd-4ca2-96ee-0ebd9f8b8855.jpg)
[log.txt](https://github.com/surge-synthesizer/surge-rack/files/8016116/log.txt)

**Comment by baconpaul** [comment]
This is almost definitely #309 
Do you have a rack log you can share?

**Comment by lancevans** [comment]
Im from Russia. In path of user folder cyrilic symbols

**Comment by baconpaul** [comment]
yes so this is the same problem as #309
