### ISSUE TITLE
Custom patch crashes VCV

### ISSUE THREAD

**Issue by intervoids** [surge-synthesizer/surge-rack#327]
I created a custom folder inside patches_factory to load my own patches ;

A few load properly, but the others are crashing VCV Pro 2.0.1, on an empty patch. 

Loading factory patches do not crash VCV.

Windows 10.0.19044

[log.txt](https://github.com/surge-synthesizer/surge-rack/files/9146264/log.txt)

Edit : patches were made with SurgeXT. I found out in the Discord that SurgePlayer is based on Surge 1.7.1. Patches made with 1.7 do not crash anymore. Idea : could this be stated on the website or VCV library ?

Edit2 : saw your post on VCV community stating that Surge rack is based on 1.7, so nevermind

**Comment by baconpaul** [comment]
Or at least the patch player will. Ids some features the plugin has
