### ISSUE TITLE
Subscribe for SurgeXT First Release Notification

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#360]
This issue exists so people can subscribe to it for notification of when the first production stable release of SurgeXT for Rack occurs.

**Comment by ndiniz2013** [comment]
Would love to know when this gets released.

**Comment by stephenbreitling** [comment]
i'm using the beta already, so of course i would like to know, when it is finally released.
if you need help, i'm not a programer, but i could help a bit with the manual.

**Comment by baconpaul** [comment]
Thank you!

I was going to write a first draft outline (at least) of the manual today. If you would like to contribute around that it would be greatly appreciated.

**Comment by baconpaul** [comment]
I submitted to the library today so Ill close this issue. It should be in the next library update.

If someone wants to help by writing the LFO section of the manual that would be great! Rest of it at least has content.

Have fun!
