### ISSUE TITLE
build fail on Mac M1 (arch64 mode)

### ISSUE THREAD

**Issue by davephillips** [surge-synthesizer/surge-rack#379]
VCV Rack v2.1.0 (local build)
Surge-Rack commit 1e1adf3b14cbc9879a22d8b2cdd129396e77ede7

Greetings ! 

Building the latest Main repo I received this error:

```
% make         
make: *** No rule to make target `dep/surge-build/src/common/libjuce_dsp_rack_sub.a', needed by `plugin.dylib'.  Stop.
```

I was able to build the required static library by running make in the indicated directory, thus enabling the build to finish. I thought you might want to note the error though.

Best regards,

Dave Phillips

**Comment by baconpaul** [comment]
OooH thank you. 

So as you saw in the README time of a lot of flux

But ... uhh ... you can run rack in arch64 mode? How do I even do that? I'm on an M1 Max and would love to avoid all the `arch -x86_64` hacks in my scripts.

**Comment by baconpaul** [comment]
Oh one other thought. If you built a previous recent version of this you will need to submodule update but if you checked out from head then would love instructions!

**Comment by davephillips** [comment]
> But ... uhh ... you can run rack in arch64 mode? How do I even do that? I'm on an M1 Max and would love to avoid all the arch -x86_64 hacks in my scripts.

Sorry about that, I meant to say x86_64. "arch64" is the script I use to set the launch directory to use Rosetta.

However, I have built VCV Rack for the M1 native CPU, but the gains weren't enough to shout about. :) There's a thread about it on the forum.

> If you built a previous recent version of this you will need to submodule update but if you checked out from head then would love instructions!

I did update the submodules. Since the error reported not finding build instructions I simply ran make in dep/surge-build/src/common/. That built both required static libs, and the plugin build could then continue to a successful close.

HTH,

dp

**Comment by baconpaul** [comment]
huh interesting. so it builds and links in our CI just fine and i build it on my M1 all the time. (like 18 times today).

let me think what could cause this. the make of surge common  *should* make that dependency.

**Comment by baconpaul** [comment]
Can you do me a favor? I just ran this

```
rm -rf dep                                   
RACK_DIR=../Rack-SDK arch -x86_64 make -j dep
ls -l dep/surge-build/src/common/*.a
```

and see this

```
paul ~/dev/music/rack/surge-rack (fx-dsp) % ls -l dep/surge-build/src/common/*.a
-rw-r--r--  1 paul  staff   26635272 Sep 15 14:55 dep/surge-build/src/common/libjuce_dsp_rack_sub.a
-rw-r--r--  1 paul  staff  135533064 Sep 15 14:56 dep/surge-build/src/common/libsurge-common.a
```

do you see the rack sub not being built by a fresh `make dep`?

if so can you send me the output of those commands and also the output of git status and the top of git log both in surge-rack and surge-rack/surge?

Thanks!

**Comment by baconpaul** [comment]
@davephillips any chance to look at this? The only thing I can think of is you had an older build before that library and our dep rules are wrong since we successfully clean build often on an M1. Any report would be great though! Thanks!

**Comment by davephillips** [comment]
Hi Paul, Sorry for the delay, I'll try to get to it today. We just became great-grandparents, so things are a little hectic here. :)

**Comment by baconpaul** [comment]
Oh wow congratulations!!! Enjoy the great grandkids.

And sorry no rush at all. We are months from a release :)

**Comment by davephillips** [comment]
Thanks, Paul ! I did a fresh git pull and rebuilt from there. No problems at all, so I'm inclined to believe that my previous build was damaged or I missed a step somewhere. Anyway, it's all good with a fresh pull, I hope that helps.

**Comment by baconpaul** [comment]
Wonderful and yes that's helpful.

If you happen to want to collaborate on the modules we could always use a hand also! As you can see it's been a few weeks of big change. But if not, enjoy these alpha versions and look for a proper release later this year :)

**Comment by davephillips** [comment]
Alas, my coding skills (?!) are better at debugging than anything else. I know how to use gdb to generate reports, including multithreaded reports, and I'm occasionally able to spot a problem. Time is my enemy, but I will let you know if/when I run into a jam. :) And thanks for all your work on Surge and your other projects. Much appreciated !

**Comment by baconpaul** [comment]
OK well bug reports are always useful! Thanks for filing this and glad we solved it!
