### ISSUE TITLE
Reverb 1 label typo

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#433]
Knob label reads DAMING instead of DAMPING.

Loving these modules, thanks to all involved.

**Comment by baconpaul** [comment]
Actually: The module has a very strong opinion on the moral nature of low pass filtering. Chuckle

anyway thanks I’ll fix it in my next merge later today. And thanks for giving them a whirl. We are feeling close to a beta for sure!

**Comment by baconpaul** [comment]
Will be fixed in next nightly, probably in about 45 minutes. This issue will close when I merge the change but thenightl taks a bit of time after that.
