### ISSUE TITLE
Mixer Module

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#443]
- [x] Implement/Hook Up Modulation
- [x] Parameter Value Display (dB for gains for instance)
- [x] Add a small VU meter below the mute/solo layers

**Comment by Andreya-Autumn** [comment]
Ok here's that probable bug report: 
1 Patch a mono cable to a channel, output is mono as expected. 
2 Then patch a poly cable to a different one, output becomes poly and adds the mono signal to each poly channel, as expected. 
3 Remove the second cable again, output stays poly with the mono signal multed to each poly channel, which is not expected.

**Comment by baconpaul** [comment]
Yeah the but I fixed in matrix is here too

https://github.com/surge-synthesizer/surge-rack/blob/662f1e99530a4f040edf4f68e8e38b0c99af3c22/src/Mixer.hpp#L194

basicalky depth never goes down. Use a temp. I can fix tonight thanks!
