### ISSUE TITLE
Latest nightly build (13/10/22) crashes linux when module browser opened

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#457]
[17.316 info src/app/Browser.cpp:194 createPreview] Creating module widget Surge XT LFO
[17.316 warn src/window/Svg.cpp:112 load] Failed to load SVG /home/ewen/.Rack2/plugins/SurgeXTRack/res/xt/dark/panels/other/LFO.svg
[18.010 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
26: ./Rack() [0x403c8d]
25: /lib/x86_64-linux-gnu/libc.so.6(+0x42520)
24: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x1051da)
23: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x108cdb)
22: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x10f779)
21: ./libRack.so(rack::app::browser::ModelBox::draw(rack::widget::Widget::DrawArgs const&)+0x494)
20: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
19: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
18: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
17: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
16: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
15: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
14: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
13: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
12: ./libRack.so(rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&)+0x34)
11: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
10: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
9: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
8: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
7: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
6: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
5: ./libRack.so(rack::window::Window::step()+0x8e2)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xbe0)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)
0: ./Rack() [0x403bb9]

**Comment by baconpaul** [comment]
Yeah wow so it seems macOS deals fine with that missing asset and win/lin don't. I'll look this afternoon

**Comment by baconpaul** [comment]
Ok I pushed a temporary fix. Curious if it works for you now either self build or latest nightly 

sorry bout this! No idea why mac deals cleanly with the failure and lin win don’t

**Comment by ContemporaryInsanity** [comment]
[5.738 info src/app/Browser.cpp:194 createPreview] Creating module widget Surge XT SpringReverb
[5.739 info src/app/Browser.cpp:194 createPreview] Creating module widget Surge XT LFO
[5.903 info src/network.cpp:147 requestJson] Requesting JSON GET https://api.vcvrack.com/library/manifests?version=2
[6.513 info src/network.cpp:147 requestJson] Requesting JSON GET https://api.vcvrack.com/modules
[6.550 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
26: ./Rack() [0x403c8d]
25: /lib/x86_64-linux-gnu/libc.so.6(+0x42520)
24: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x1045da)
23: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x107bb3)
22: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x10e2a9)
21: ./libRack.so(rack::app::browser::ModelBox::draw(rack::widget::Widget::DrawArgs const&)+0x494)
20: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
19: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
18: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
17: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
16: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
15: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
14: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
13: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
12: ./libRack.so(rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&)+0x34)
11: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
10: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
9: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
8: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
7: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
6: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
5: ./libRack.so(rack::window::Window::step()+0x8e2)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xbe0)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)
0: ./Rack() [0x403bb9]

**Comment by baconpaul** [comment]
Huh ok 

do you self build? Would love to see that without stripped

but it will have to wait until this afternoon most likely

**Comment by ContemporaryInsanity** [comment]
No, grabbed latest from here.

Good hunting.

**Comment by baconpaul** [comment]
OK I just did a push which basically totally disables those widgets which seem to be causing the crash

Should be new nightly in ~20 mins

Then I can debug at leisure tomorrow on an actual linux box

Thanks for the report and let me know if you are back in the water.

**Comment by ContemporaryInsanity** [comment]
That runs, thanks.

**Comment by baconpaul** [comment]
Excellent thanks

**Comment by baconpaul** [comment]
Ahh booted into Linux and found it. New nightly coming soon enough with these back on.

**Comment by ContemporaryInsanity** [comment]
Still an issue somewhere, can't reliably recreate this, it crashed rack when selecting treemonster from the browser, restarted, tried again, fine.

Log:

[10680.776 info src/app/Browser.cpp:86 chooseModel] Creating module Surge XT TreeMonster
[10680.776 info src/XTModule.hpp:56 showBuildInfo] [SurgeXTRack] Instance: Module=FX<Treemonster> BuildInfo=os:linux pluggit: surgegit:c52186d buildtime=Oct 13 2022 22:41:42
[10680.795 info src/XTModule.hpp:91 setupSurgeCommon] [SurgeXTRack] storage::dataPath = '/home/ewen/.Rack2/plugins/SurgeXTRack/build/surge-data/'
[10680.795 info src/XTModule.hpp:92 setupSurgeCommon] [SurgeXTRack] storage::userDataPath = '/home/ewen/Documents/Surge XT'
[10680.799 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
24: ./Rack() [0x403c8d]
23: /lib/x86_64-linux-gnu/libc.so.6(+0x42520)
22: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x2f9b5e)
21: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x35615e)
20: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x356389)
19: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x174572)
18: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x174863)
17: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x175eb5)
16: ./libRack.so(+0x387136)
15: ./libRack.so(rack::app::browser::ModelBox::onButton(rack::widget::Widget::ButtonEvent const&)+0x2a9)
14: ./libRack.so(rack::widget::Widget::onButton(rack::widget::Widget::ButtonEvent const&)+0xed)
13: ./libRack.so(rack::widget::Widget::onButton(rack::widget::Widget::ButtonEvent const&)+0xed)
12: ./libRack.so(rack::widget::Widget::onButton(rack::widget::Widget::ButtonEvent const&)+0xed)
11: ./libRack.so(rack::ui::ScrollWidget::onButton(rack::widget::Widget::ButtonEvent const&)+0x103)
10: ./libRack.so(rack::app::browser::Browser::onButton(rack::widget::Widget::ButtonEvent const&)+0xfd)
9: ./libRack.so(rack::ui::MenuOverlay::onButton(rack::widget::Widget::ButtonEvent const&)+0x11d)
8: ./libRack.so(rack::widget::OpaqueWidget::onButton(rack::widget::Widget::ButtonEvent const&)+0x105)
7: ./libRack.so(rack::widget::EventState::handleButton(rack::math::Vec, int, int, int)+0x269)
6: ./libRack.so(_glfwPlatformPollEvents+0xdfc)
5: ./libRack.so(rack::window::Window::step()+0x5c)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xbe0)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)
0: ./Rack() [0x403bb9]

**Comment by baconpaul** [comment]
yeah i see occasional crashes also. i need to run through a sanitized. it hoguth I fixed a bunch of em yesterday but seems there's still some to go.

**Comment by baconpaul** [comment]
I moved this class of problem to #462 since this one was a separate module browser issue only.

**Comment by baconpaul** [comment]
Asan turned up a big smoking gun of an error in the fx classes which I will fix this morning

I’ll leave the other issue open for any other crashes. I tested the rest of the modules and think that fx corruption was the primary problem but also fixed a few other things
