### ISSUE TITLE
FM3 VCO tooltip error

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#475]
M3 RATIO tooltip shows frequency.

**Comment by baconpaul** [comment]
That's actually correct. M3 in FM3 is absolute. But the label should be changed to M3 FREQ which I'll do!

( You can swap M1 and M2 to absolute also if you want, in the RMB menu )

**Comment by baconpaul** [comment]
Ok just merged a fix for both of these, thanks - keep ‘em coming! Super useful
Usually takes 20 minutes or so to make a new nightly. But the process is started
