### ISSUE TITLE
Visual bug on LFO sliders.

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-rack#508]
Found a little one. Clicking and dragging the LFO module EG sliders all the way up or down, will show the number hitting 0 or 100%, but the slider stops short of that position. Next click on the slider sometimes jumps it to the min/max position. 

Seems it's visual only. Actual signal is ok I think.

**Comment by baconpaul** [comment]
oh yeah i see that. huh. wonder what event isn't getting sent. I'll change the stale check and that will fix it.
