### ISSUE TITLE
Request: Sync for Delay times 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge-rack#51]
Sync for Delay times to vcv clock  in dualdelay module in rack ..

**Comment by baconpaul** [comment]
So here’s how I think I would do this

The Params for fx unclear if they even have extended range but some have temposync. So check that fact

Then add another little switch which is enabled if yemposync can be turned on for a param

And add a cv I put for clock which I convert to non using the same math as seq3 and polygnome

**Comment by sense-amr** [comment]
makes sense to me .. so a sync in port ?

**Comment by baconpaul** [comment]
a clock in port.
you put the "clock" output from seq3 in and then it has the same bpm as seq3. (or poly gnome or any other clock source).

**Comment by sense-amr** [comment]
yep gotcha i was just trying to confirm the ui method you had in mind :) .. awesome .. 
so the use of the clock input would then dictate the knobs to be "synced" to clock values? and the absense of the use of the clock input would then leave those knobs as delay time etc.. to be free?

**Comment by baconpaul** [comment]
Nah My plan is (since the 'expanded range' doesn't actually apply to any fx params) is to activate the little toggle if you can TempoSync and let you swap it. Then change the display accordingly and stuff.

**Comment by sense-amr** [comment]
yes well its not currently being used so why not :D
