### ISSUE TITLE
Feature request: Selective randomization.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#524]
I'm a huge fan of randomizing modules, typically using Stoermelder Strip.

Randomizing Surge XT modules with options to not randomize modulation / gain settings would be nice.

My limiter would thank you :)

**Comment by baconpaul** [comment]
Ahh right.  Let me look at that API.

**Comment by baconpaul** [comment]
So basically this amounts to : turn randomization off on the entire mod matrix and a few select gain things? And that seems to be done with `auto p = configParam(foo); p->randomizeEnabled = false;'

I can at least turn it *off* judiciously before we ship version 1.0

**Comment by ContemporaryInsanity** [comment]
Vult's fault: https://community.vcvrack.com/t/vult-announcements-thread/1763/192

**Comment by baconpaul** [comment]
```cpp
    template<typename T=rack::ParamQuantity, typename ...Args>
    rack::ParamQuantity *configParamNoRand(Args... args){
        auto *res = configParam<T>(args...);
        res->randomizeEnabled = false;
        return res;
    }
```

in my base class means I can just sprinkle 'NoRands' around the code.

**Comment by baconpaul** [comment]
OK this was actually super easy. I added it and applied it with some discretion to some modules. So I'll close this

but full warning; Holding Apple-R down in the LFO module crashes. I need to debug why. I will open a separate issue for that.

**Comment by baconpaul** [comment]
Oh and new nightly an hour or so from now.

Holding down randomize on the filters and VCOs is fun.

**Comment by baconpaul** [comment]
just pushed the lfo fix also - randomization is now pretty reasonable. 

#527 would be nice but that's for after 1.0
