### ISSUE TITLE
Delay time precision 

### ISSUE THREAD

**Issue by docb** [surge-synthesizer/surge-rack#533]
Hi,
i have tried out the current build.
In my default template i have connected the Bpm output from PwmClock to the Clock input of Surge Delay
and was able to set the delay times in terms of fractions. Is this gone?
The display should also show more than precision 2 as e.g 370ms appear as 0.37.
 Thx.

**Comment by docb** [comment]
ah sorry got it, its in the menu

**Comment by baconpaul** [comment]
The precision point is a good one. I’ll reopen this issue so I remember to add that today

**Comment by baconpaul** [comment]
And yes we default clock inputs to ppq triggers which seems more idiomatic and require a switch to make them do bpm. That swirch saves and so on but if you used an older version of delay we changed some params which could have broken streaming. (Today is beta day which means today we are freezing streaming comparability so you will be fine if you set it once now)

**Comment by docb** [comment]
Yes, maybe you should mention that the CV input has changed to 0V=120BPM was 60BPM before.

**Comment by baconpaul** [comment]
yeah the old surge modules followed the wrong standard; the new ones follow the vcv voltage standards and work fine with clocked (which has been my test clock). We will add this to the manual indeed (when we write it this month :) )
