### ISSUE TITLE
Wavetable with Mis-Installed surge (no .wt files) crashes rather than produces a clean error

### ISSUE THREAD

**Issue by docb** [surge-synthesizer/surge-rack#535]
hi, overall great stuff!
i don't know if it is the right time for reporting such bugs, but i cannot open wavetable vco, window vco as it crashes when clicking in the browser on those modules (on linux ubuntu) 

```
Thread 1 "Rack" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5ff3800 (LWP 445798)]
WavetableOscillator::convolute (this=0x55555b8efee0, voice=<optimized out>, FM=<optimized out>, stereo=<optimized out>)
    at /home/docb/git/Rack2/plugins/surge-rack-xt/surge/src/common/dsp/oscillators/WavetableOscillator.cpp:292
292	    newlevel = distort_level(
(gdb) backtrace
#0  WavetableOscillator::convolute (this=0x55555b8efee0, voice=<optimized out>, FM=<optimized out>, stereo=<optimized out>)
    at /home/docb/git/Rack2/plugins/surge-rack-xt/surge/src/common/dsp/oscillators/WavetableOscillator.cpp:292
#1  0x00007fffcf815db0 in WavetableOscillator::process_block (this=0x55555b8efee0, pitch0=<optimized out>, drift=<optimized out>, stereo=false, 
    FM=<optimized out>, depth=0) at /home/docb/git/Rack2/plugins/surge-rack-xt/surge/src/common/dsp/oscillators/WavetableOscillator.cpp:485
#2  0x00007fffcf46d246 in sst::surgext_rack::vco::ui::OSCPlotWidget<2>::recalcPath (this=this@entry=0x55555b8ef9e0) at src/VCO.cpp:505
#3  0x00007fffcf46d570 in sst::surgext_rack::vco::ui::OSCPlotWidget<2>::step (this=0x55555b8ef9e0) at src/VCO.cpp:324

```

**Comment by docb** [comment]
ah ok, i didn't install at all. i built it inside the Rack plugins folder and run Rack -d

there appeared some directories in the Documents/Surge XT folder but they are all empty.

**Comment by baconpaul** [comment]
Right you need to do an install to find all the assets or at least a make dist 

if that works I will rename the issue to be don’t crash when there’s no wavetables and fix that edge case

**Comment by baconpaul** [comment]
Right you need to do an install to find all the assets or at least a make dist 

if that works I will rename the issue to be don’t crash when there’s no wavetables and fix that edge case

**Comment by docb** [comment]
ok, make dist solved the issue! thanks.

**Comment by baconpaul** [comment]
Added a workaround to avoid the crash when mis-installed also. They won't work but they won't segv. Thanks for reporting!
