### ISSUE TITLE
Rotary Preset

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#536]
Seems that Surge 1.7 had a rotary preset which is missing. Did we just mis-port it to 1.7?

> Georg Carlson ​@Baconpaul what happened to the Warm Rotation preset on the Rotary? Miss that one for Phil Lesh style bass treatment

**Comment by fractalgee** [comment]
2.1.7 Surge for Rack Rotary had the following presets:

Distorted Doppler
Subtle
This Is Not What Leslie Wanted
Warble
Warm Rotation

last one is the one I miss as it is very close to what Phil Lesh had his set to for his bass to my ears. Would love it back.

**Comment by baconpaul** [comment]
Yeah I've found the vcvm files in the old repository. The new mechanism is different and funnily I made this presets for rack but never pushed them back to surge proper which is where we now get our presets from so they all match

I'll take them and make them Surge presets (or improved surge presets) and then update before we hit the library. I'll close this issue also when it's done so you can know to update. 

Thanks for flagging it!

**Comment by fractalgee** [comment]
all good, glad another possible 'oops, broke some patches' issue is sorted
then :)
