### ISSUE TITLE
Build error on Win11, msys2-mingw64

### ISSUE THREAD

**Issue by jpnielsen** [surge-synthesizer/surge-rack#540]
Building under /rack/plugins (fresh git clone of rack 2.1.2)

gcc version 12.2.0 (Rev5, Built by MSYS2 project)

```
make dep


[ 44%] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Hombre.cpp.obj
H:/msys64/home/jpn99/github/Rack/plugins/surge-rack/surge/libs/sst/sst-plugininfra/src/paths_windows.cpp: In function 'std::filesystem::__cxx11::path sst::plugininfra::paths::sharedLibraryBinaryPath(
':
H:/msys64/home/jpn99/github/Rack/plugins/surge-rack/surge/libs/sst/sst-plugininfra/src/paths_windows.cpp:49:15: error: 'vector' is not a member of 'std'
   49 |     for (std::vector<WCHAR> buf{MAX_PATH};; buf.resize(buf.size() * 2))
      |               ^~~~~~
H:/msys64/home/jpn99/github/Rack/plugins/surge-rack/surge/libs/sst/sst-plugininfra/src/paths_windows.cpp:12:1: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector
'?
   11 | #include <shlobj.h>
  +++ |+#include <vector>
   12 |

```

Fixed by adding in [paths_windows.cpp](https://github.com/surge-synthesizer/sst-plugininfra/blob/a3f2a93857e7359074567a1255890c667dd40cec/src/paths_windows.cpp#L12) after line 11 :
**`#include <vector>`**

**Comment by baconpaul** [comment]
Thanks! You are I believe the first person on the planet to compile surge on windows with gcc 12 :)

I will push this through the submodules and update this weekend. Appreciate the report

**Comment by baconpaul** [comment]
anyway walked that include through
if you pull main, submodule update, blow away 'dep/surge-build` and try again it should all work
thanks for the clear report including the fix. Appreciated.
