### ISSUE TITLE
Envelope generator can produce a nasty click on repeated triggers

### ISSUE THREAD

**Issue by Rcomian** [surge-synthesizer/surge-rack#541]
Using LFO x EG as an envelope, If the release phase has not completed and returned to 0 when the next note is triggered, the envelope is immediately forced to 0 to start the next envelope shape.

This causes the VCA to close abruptly with a click that can't be tuned out except by having a release shorter than any delay between notes.

![image](https://user-images.githubusercontent.com/684678/199845252-b470c83f-80c0-4e95-829b-32286be1a0a3.png)

This is a screenshot of the scope showing the LFO x EG behaviour in blue compared to the VCV ADSR being triggered by the same gate in purple. The gate is also shown in purple for illustration.

Note in blue that the LFO x EG raises correctly according to the attack when the gate goes high. The LFO x EG also starts falling in the release phase correctly once the gate goes low. However, when the gate goes high again, before the release has gone to 0, the envelope is forced to 0 and next attack starts from 0. This is the cause of a click.

Compare with the VCV ADSR output. The output level falls in the release phase correctly, but when the gate goes high again, the attack phase starts from where the output was, rather than forcing it to 0. This means the attack phase is truncated, but that's largely what's expected when playing notes rapidly. This is one way to address the issue, there may be others.

However, the current operation can cause a nasty clicking in situations where clicks don't happen for much less capable envelope generators.

The only way to tune it out is to put a slew limiter on the EG output or to add filter after the vca to reduce most of the click. Neither of which are very nice solutions.

I've attached a patch which demonstrates the issue.

[ClickyEG.vcv.txt](https://github.com/surge-synthesizer/surge-rack/files/9933427/ClickyEG.vcv.txt)

**Comment by baconpaul** [comment]
Yeah this is just kinda what the surge eg does. I thought about fixing it in both surge and surge rack so will leave this open but this is behavior which would match the vst in mono mode 

obviousky if you use the lfo polyphonically this problem will resolve 

I’ll think about what to do and will tag this as a feature request (and a reasonable one) for now

**Comment by baconpaul** [comment]
Here's my plan of attack

In surge:

1. Add `LFOModulationSource::attackFromEnvelope(float sp)` and `retriggerEnveloepFromEnvelope(float sp)`
2. Add `float attackStart{0}, attackSlope{1};`
3. Make `attack` and `retriggerEnv` call `attackFromEnvelope(0)` and so on
4. attackFromEnvelope sets the start to sp and the slope to 1-sp basically
5. In the delay phase output the start value
6. in the attack phase output the (original attack) * slope + sp. But check that math
7. Merge sweep
8. Open an issue in surge proper to make that mode callable in the continuous mono play modes but leave surge alone

In surge-rack

```cpp

                 if (inNewAttack)
                 {
+                    std::cout << "ATK: Env Level is " << surge_lfo[c]->get_output(2) << std::endl;
                     surge_lfo[c]->attack();

...

 else if (inNewEnvAttack)
                 {
+                    std::cout << "ETK: Env Level is " << surge_lfo[c]->get_output(2) << std::endl;
                     surge_lfo[c]->retriggerEnvelope();
```

make those pass that output down. (Those prints to TRT)

2. Add a module bool for 'surge-style-retrigger' or 'continuous-retrigger'which chooses whether to use getoutput(2) or 0
3. make the default continuous-retrigger

voila

**Comment by Rcomian** [comment]
that's nice, one thing with the math is that it's possible to make the slope non-linear in the LFOxEG output by changing the deform parameter. This would alter the math in locating the crossover point. It would be a lot closer, so the click would be quieter, but maybe a thing to consider.

I was trying to see the surgext's native behaviour but i wasn't able to work out how to make that synth work in the main ui. By default it has a dedicated basic AMP ENV that seems to work more like "normal".

**Comment by baconpaul** [comment]
Yeah they deform accommodation is why I didn’t do it indeed but we did it elsewhere and can do it here too 

Take an lfo and make it an envelope in the vst basicalky. The ampeg already is continuous it’s just the modulator env which isn’t

**Comment by baconpaul** [comment]
<img width="1328" alt="Screen Shot 2022-11-05 at 4 00 00 PM" src="https://user-images.githubusercontent.com/13387561/200138774-8f7f96dd-a92b-44e4-994d-a8e92f12e7e0.png">

There you go

Will merge shortly

I think I got all the cases with deform correct also but if not after the next build please do open a new issue.
