### ISSUE TITLE
Some module LED's are missing labels.

### ISSUE THREAD

**Issue by jpnielsen** [surge-synthesizer/surge-rack#543]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/27916597/199878540-9b20d845-05b7-449c-bb62-1b49372e67ee.png">

The little toggle LED's are missing meaningful labels (right-click) - and the Label + Value doesn't show on mouse-over like other controls. Perhaps it's redundant, 1=bright, 0 =dim. If there is a text on mouse-over, it will be less guess-work that the circles are LED's and toggle on/off when clicked.

The LED's/controls are named` "#27" and "#28".`

**Comment by jpnielsen** [comment]
same problem with "#42" and "#43" on "Windows VCO"

**Comment by baconpaul** [comment]
Thanks for this detailed report! Appreciated

**Comment by baconpaul** [comment]
Thank you - fix in place. While fixing I also fixed the bug that suppressed the tooltip on these controls; and made the oaram quantity display as on/off (and accept typein as on/off or 0/1)

should all be in the updated binary within an hour or less
