### ISSUE TITLE
Q: General question regarding perfomance

### ISSUE THREAD

**Issue by docb** [surge-synthesizer/surge-rack#545]
as great these modules are, they seem to need a lot of CPU especially with polyphony.
is this topic on the list for future releases? is there room for enhancement?

**Comment by baconpaul** [comment]
So there's a couple of things you can do, especially wavetable unison and vintage ladder are expensive, so keep unison low or be parsimonious with the vintage ladder. At very high polyphony on the LFOs you can also get some performance by quality degrading the downsampling filter in the RMB.

But a long wavetable high unison high polyphony use case is a high CPU case in surge vst and surge rack both.

Beyond that, some more specifics would help. Like - classic uses very little CPU but modern uses more. Which ones are giving you problems?

and finally: yes performance can always be better but the profile we have today is the one we intend to ship for 1.0 and is basically the same one the VST exhibits (except for downsampling load at high polyphony in the VCOs)

**Comment by baconpaul** [comment]
oh and i intend to write a section for the manual on 'taking CPU load'. I may write that ahead of the rest since we have had a few questions pop up.

**Comment by docb** [comment]
yes ok,  i wondered about 3.1% for 4 voices and 6.2% with 4x unison with the Modern VCO 
and about 2.7% in Wavetable VCO. but may be they are more complex than i thought.

**Comment by baconpaul** [comment]
They are 

they all run at 2x oversampling with a variety of alias suppressing techniques. Classic is probably the lightest but these aren’t naive implementations. That said they are quite well tuned for what they have to do. With modern we spent a lot of time staring at assembly output and organizing the code appropriately

**Comment by baconpaul** [comment]
I think #505 is the open issue where I think I can get some more performance, but it sounds like you are seeing about what we see in the VST and in rack also so I'll close this issue; but happy for you to open issues on specific  modules which you think mis-perform especially once I get that CPU usage section of the manual written.

Thanks for the feedback and for using surge!
