### ISSUE TITLE
Selector triangles acting unintuitively 

### ISSUE THREAD

**Issue by firolightfog** [surge-synthesizer/surge-rack#546]
I'm testing VCV Rack Free 2.1.2 with Surge XT 2.xt-1.1.1-nightly-0ad9e34. 

It seems to be a GUI issue:
- Pressing 3x the right arrow loops through the options. (With restart.)
- Pressing 3x the left arrow steps one-by-one to the first option. (Without restart..)

<img width="157" alt="image" src="https://user-images.githubusercontent.com/34127628/199943443-1c5db472-52c2-435d-88c1-b0476f75a887.png">

**Comment by baconpaul** [comment]
Oh I bet it is thinking it gets a double click. Thanks

**Comment by baconpaul** [comment]
Oh no this is different I see. We don't wrap around the negative side in the sub-type selector. Got it. Thank you.

**Comment by baconpaul** [comment]
Ha here's the 2 character fix:

```cpp
diff --git a/src/VCF.cpp b/src/VCF.cpp
index dc7f9bd..59b5136 100644
--- a/src/VCF.cpp
+++ b/src/VCF.cpp
@@ -229,7 +229,7 @@ struct VCFSubtypeSelector : widgets::ParamJogSelector
 
         i += dir;
         if (i < 0)
-            i = sst::filters::fut_subcount[type];
+            i = sst::filters::fut_subcount[type] - 1;
         if (i >= sst::filters::fut_subcount[type])
             i = 0;
```

I'll merge that in my next sweep and close this issue. Thank you.
