### ISSUE TITLE
Add Bloom to the small LEDs (was: Use of Light Effects)

### ISSUE THREAD

**Issue by jpnielsen** [surge-synthesizer/surge-rack#548]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/27916597/199958501-6e3d6000-1310-4c6e-8729-e1c753af1fe5.png">

The texts on the LED displays don't light up, and there's no bloom on your small LED toggles.

A design choice ?

**Comment by baconpaul** [comment]
The texts are a design choice yes. We wanted a limited presence in the bloom layer.

The bloom is an oversight. I'll take a look.

Thank you!
