### ISSUE TITLE
Request: Double left mouse click resets to 0 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge-rack#55]
request to implement zeroing of parameters on knobs .. as is with surge synth

**Comment by sense-amr** [comment]
i guess this actually means rest knob to "middle" for alot of parameters.. including pan .. 
i should clarify not all are "0" 
but i was meaning to implement same as surge synth .. for knob reset..on double left mouse click

**Comment by baconpaul** [comment]
The right mouse gesture in rack v1 gives you this basically for free on the knobs (just different gestures). I need to do #147 to customize them with proper zero points and stuff but will do that there, so am closing this.
