### ISSUE TITLE
LFO Step Edit Gestures

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#559]
Talking with @contemporaryinsanity over in #557 we said

> > Also, click to set step on step sequencer would be faster than click & vertical drag.
> >Bonus points for click & horizontal drag to draw shapes, see voxglitch sequencers.

> Yeah surge proper has all these features and more (including things like quantized drags to 1/12 and draw an arrow for a line). Porting them is hard - especially since I did each as a slider - but let me open a separate issue for this and put it mostly post 1.0.

**Comment by baconpaul** [comment]
I at least will get click-to-set into the next release later this weekend. Have it working on my branch now.

**Comment by ContemporaryInsanity** [comment]
Same in Alias VCO additive edit would be nice, or at least click to set instead of drag.

**Comment by baconpaul** [comment]
Oh did I not copy that gesture over? Sorry about that. Let me toss this into 2.1 so I can look next cycle

**Comment by baconpaul** [comment]
@ContemporaryInsanity click to set works on the alias bars for me at head and in 2.0.3.0 - does it not for you?

So I'm going to move this back out of 2.1 since click to set works everywhere at least.

**Comment by ContemporaryInsanity** [comment]
I grab the auto build whenever I note it has changed so I'm on SurgeXTRack-2.1.beta.0-nightly-ec2af67-lin-x64.vcvplugin
Click to set has never worked for me.

**Comment by baconpaul** [comment]
has never worked in either LFO or Alias?

**Comment by ContemporaryInsanity** [comment]
Single click does nothing in either, double click resets to default.

**Comment by baconpaul** [comment]
huh wow
ok lemme test it on linux
single click works wonderfully on macOS which is why i shifted this issue out of milestone!

**Comment by baconpaul** [comment]
oh huh indeed it doesn't work on linux.
wonder why
lemme try and fix that

**Comment by baconpaul** [comment]
Sigh OK what's happening is macOS and Linux are sending me different events in my sub-classing of SliderKnob onButton and linux doesn't send me the release unless I unconsume the event; but unconsuming the event means I don't get drags.

So I will have to rewrite this slider control to not be a sliderknob at all and just re-do the gestures consistently I guess.

Thanks for flagging. I'll add a new issue to 2.1 for this so we can keep the extended gestures separate.

**Comment by baconpaul** [comment]
So it turns out its easier to just do the full multi-param widget than it is to just fix that event consume on slider

Still using a test renderer, but this will get done before weekend along with most of the other surge gestures (like shift and ctrl and alt drags).

Will probably skip line drawing and add an RMB but basically I'll close out #668 and just put the full shebang into 2.1

![StepEditYay](https://user-images.githubusercontent.com/13387561/204933528-ca44118e-8440-411c-ab51-ae133eb0a0c0.gif)

**Comment by baconpaul** [comment]
OK the next nightly will have greatly improved editors. Still a few things to go but way better already. Will close this issue and just leave the 2.1 minor stragglers issue open.
