### ISSUE TITLE
Treemonster tuning cv out

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#563]
> how interesting would it be to do a CV (and gate?) output on tree monster? there is room. or an extra  module  audio to cv converter using TM tech?

says pyer. And it is a good idea

**Comment by Andreya-Autumn** [comment]
Yup! It's a good idea. Either a v/oct output or the carrier wave as a separate audio output maybe? Or both?

**Comment by baconpaul** [comment]
I could also just implement the pitch detection and envelope tracing algorithm as a separate module altogether, is another thought we had.

**Comment by Andreya-Autumn** [comment]
How about do that, plus give Treemonster proper a carrier wave output? Then between those two modules all function outputs are available without having to bloat the treemonster panel.

The carrier wave output of course shouldn't really be any different than just patching those detection algo CV's to any sine VCO, so the only point in including it is saving the user some space when they want to use that carrier separately. Sometimes useful, but maybe not super important. The more I think about it the more I like the idea of the separate Treemonster tech module. :)

**Comment by baconpaul** [comment]
yeah it may be the answer indeed.
the panel space is a bit tight. I asked pyer for some ideas.

**Comment by baconpaul** [comment]
[SVG.zip](https://github.com/surge-synthesizer/surge-rack/files/9964510/SVG.zip)

there's panels with an extra output position from pyer if I decide to go panel vs self draw for the output region

**Comment by baconpaul** [comment]
Just merged this into the nightly
