### ISSUE TITLE
Single Click on Unison etc pops a menu

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#568]
> I’m not a fan of the dragable labels for Oct and Uni. I think at least a click on them should pop a menu like the wave selection labels.

**Comment by rubyglow** [comment]
Works in latest nightly, thanks!
Only minor nit is that it swallows double-click to reset the setting to default. If that's unavoidable then it's fine. If it's cheap to distinguish between single and double-click in the code, I think that's worth doing.

**Comment by baconpaul** [comment]
Oh let me reopen and see if I can. I think I did elsewhere

**Comment by baconpaul** [comment]
Thanks for the comment. The next nightly will have double click restored, at the expense of about a 150ms latency on opening the menu while we wait around to see if a second click is coming. This issue will close automatically when I merge the change.
