### ISSUE TITLE
Simple Attenuator in the menu next to drift for VCOs?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#569]
> In unison modes they can deliver a quite high output level. I wonder if an output level knob would be appropriate, where there’s space. Otherwise we really need attenuators right after the VCO.

**Comment by rubyglow** [comment]
Works in latest nightly, thanks!

In thinking about the user experience a bit - although the menu based attenuator works, a user might only discover this when plugging in a scope, or looking at a mixer VU meter. It's not that I want to give you guys more work but....

Is there any cheap way of having say a red LED as "overload indicator" when output exceeds 10v p2p? Could be a small one centered between the Left/Right output ports.

Also, ideally it would be much better usability to have the output attenuator knob right on the faceplate. But I realize some of those faceplates are full now so a menu item it is.

As always, thanks for your brilliant work!
Regards, Lars

**Comment by baconpaul** [comment]
Yeah I certainly didn’t want to change all the faceplates this late in the beta cycle which is why the menu item ended up working 

I’ll open a separate issue for after 1.0 for an overload light and attenuator position
