### ISSUE TITLE
Optional DC Filter on the back of the VCOs

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#570]
Maybe?

> I would really like a DC filter on the outputs, as many of the VCO’s have quite a DC-offset in some modes. Could be optionally engaged from a context menu, if it uses CPU.

**Comment by rubyglow** [comment]
Tested on SurgeXTRack-2.xt-1.1.1-nightly-b10afec-mac.vcvplugin

Yup, the DC-offset is fixed, or in the case of String VCO quite reduced.

In testing this on my aging CPU I find that the DC blocker consumes no CPU what so ever, and like Squinky I would argue that it should just be turned on by default, and that in fact that menu item is likely not needed at all.

Test patch (remove .zip extension) and picture of before/after reproduction attached.

Thank you for the fix!
All the best, Lars Bjerregaard

[Testing-DC-offset.vcv.zip](https://github.com/surge-synthesizer/surge-rack/files/9945723/Testing-DC-offset.vcv.zip)

![Testing-DC-offset](https://user-images.githubusercontent.com/38786343/200168424-cd70dc82-4c82-47a7-ac47-8446820a1c7e.png)

**Comment by baconpaul** [comment]
Excellent thank you.

I keep thinking of omri using FM3 as an ultra-low-frequency oscillator-as-LFO in his video so I think we will want the menu item; the blocker does change shapes if you send pitch to extrema and octave to extrema. But I'm leaning to default on also. I'll play with it today and make a call.

This is one of the things you don't think of when you de-compose an entire running synth signal path. Who cares about a bit of DC when you have HPF downstream anyway etc... so appreciate the careful input here.

**Comment by baconpaul** [comment]
Thanks for the tests. Very useful and confirmative

The next nightly will default the blocker to on but leave the menu in place. This issue will close when I merge it.
