### ISSUE TITLE
Modulation and Parameter names wrong in mapping tools

### ISSUE THREAD

**Issue by jpnielsen** [surge-synthesizer/surge-rack#573]
I love building interfaces for my patches in TouchOSC or OpenStageControl.

I haven't really done much with the Surge XL modules yet - but I see that the "MOD #" buttons are not map'able:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/27916597/200143133-52edb9a7-bbd3-4b2d-b8d6-32b2ff59b0e4.png">

If at all possible, please make the modules compatible with OSC and MIDI mapping, using the VCV [MIDI-MAP](https://library.vcvrack.com/Core/MIDI-Map), Stoermelder [[uMAP|CV-MAP](https://library.vcvrack.com/Stoermelder-P1) ], TheModularMind[[OSCelot](https://github.com/The-Modular-Mind/oscelot)] or [ModScript ](https://github.com/Simon-L/ModScript)Modules.

**Comment by baconpaul** [comment]
They are hidden unless armed

If you arm them (with the mod button) they will replace the knobs and then you can map them (or at least I could with the midi mapper when I tried a few weeks ago).

So if you want to midi control mod 2 -> phase, click the button above mod2 phase will change to the arm knob, then mod that.

![HowToMapMods](https://user-images.githubusercontent.com/13387561/200143518-0a70257d-51c9-4411-bac8-7842214d77a8.gif)

I'm not sure why the midi mapper isn't picking up the name with this gesture though. I'll dig into the code and try and find that out. I am using custom param quantities so maybe there's some other API it uses I don't expect even though the tooltips are all OK.

**Comment by baconpaul** [comment]
Oooh I see why. Bad Rack. They use `paramQuantity->name` rather than `paramQuanitty->getLabel` and the surge modules provide the second. I can fix that

**Comment by baconpaul** [comment]
OK so the real problem here is if I push getLabel to name then it recurses since getLabel calls name

So I need to restructure all the surge params basically to have a little interface and then in widget::step to check if the current name differs and push it over and so on. ugly but not impossible. Changing the subject (since the mapping works just not the name) and pushing it into the 1.0 milestone.

Thanks for the report. I hadn't tested mapping since I fixed all the names.

**Comment by baconpaul** [comment]
OK the next nightly will have the names correct in the midi mapper and can map modulation levels properly. Presuming that ocelot uses basically the same mechanism you should be all good! This issue will auto close when I merge the change and the nightly will follow about 30 minutes after that.
