### ISSUE TITLE
LFO x EG Step Sequencer sliders

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#582]
With UNI on dragging the sliders from top to bottom goes from 1 to 0, once you've hit 0 & keep dragging it then continues to -1 as if UNI was off, not a problem (output works as expected) but potentially confusing / not quite perfect.

**Comment by baconpaul** [comment]
oh thank you!

(Internally it still allows values < 0 in uni mode but the editor should suppress those gestures indeed).
