### ISSUE TITLE
One shot uis

### ISSUE THREAD

**Issue by paulpiko** [surge-synthesizer/surge-rack#584]
Using SurgeXTRack-2.0.beta.0-nightly-dd6ebb9-win.vcvplugin, Windows10

On selecting one of the Oneshot waves, Wavetable VCO stops outputting anything. Selecting another wave from then does not fix it; it remains that way until Rack is restarted.

**Comment by paulpiko** [comment]
Also happens with EMU VSCO Oneshots

**Comment by baconpaul** [comment]
Ooh the re select should work
But one shots are one shots. You need to trigger the oscillator to make them shoot.

**Comment by baconpaul** [comment]
Yeah when switching from one-shot to non-one-shot you need to send a trigger to get the wave back; and when switching from non-one-shot to one-shot you need to trigger to start shooting. that's a real bug. I'll fix it this week. Thank you.

I'll also add a visual indicator that it is a one-shot and perhaps even change the label from "RESET" to "TRIG" when one shots are loaded.

**Comment by baconpaul** [comment]
OK I'm going to merge the DSP bug in the next nightly which caused it to not reset properly when you change wavetables
but I'll leave this open to get the visual indication of one shot and change the label to TRIG when you load one.
