### ISSUE TITLE
See: Removing unnecessary context menu options? in VCV community forum

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#589]
![image](https://user-images.githubusercontent.com/12547379/200376398-abe9679f-9ef5-47b6-a382-24412b2b2a3a.png)

https://community.vcvrack.com/t/removing-unnecessary-context-menu-options/18664

**Comment by ContemporaryInsanity** [comment]
Reverb 1 shape missed:

![image](https://user-images.githubusercontent.com/12547379/200548052-aa6e7a07-6a67-43ab-8d18-533fc2fdce8b.png)

**Comment by baconpaul** [comment]
Ahh. Yeah there’s a reason for that. I’ll reopen this but unfortunately the switch trick won’t work there so may not be easy to fix

really appreciate this detailed feedback

**Comment by baconpaul** [comment]
yeah it is lot less elegant a solution but i got it working :)
Should be in the next nightly.
