### ISSUE TITLE
A New VCAxEG Module

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#598]
# BaconPaul Edit: The ToDo List

## Display area

- [x] In the display, please add a grey horizontal divider line below the top section (below Mode and Curve controls). Same position and size as on Quad AD. This will be consistent and will help to visually separate the Analog/Digital buttons (which relate to the envelope) from the VCA level meter. 
- [x] Add padding around the envelope shape at top and right side so there is some space between it and the grey divider lines.
- [x] Probably also add some padding at top of VCA level meter so there is some space between it and the new grey horizontal line added below top section.
- [x] Move envelope shape down slightly so bottom of envelope shape and VCA level meter are aligned (in default state when instantiated)
- [x] I'm a little uncomfortable with the envelope curve shape controls - they look a little busy due to the height variation and I think they could be simplified. Perhaps they just need a little padding added above them so they are not quite so close to the top of the display. But I think they might work better if they were all on the same horizontal line  - in other words no height differentiation between the decay and release controls - just 3 angled lines in a row like:  /  \  \

 
# Original Message
------

Lots of chatter about a stereo VCA; I suggested the mixer and it works well but in chats with steve and evil we came up with:

<img width="418" alt="Screenshot_2022-11-08_at_18 50 41" src="https://user-images.githubusercontent.com/13387561/200656290-0fd19e0f-dcab-446a-92e0-9594fd8347f0.png">

VCO type layout with 8 knob (area) and big display (with env shape and level meters)
ADSR as either 4 knobs or 4 sliders taking up the same amount of space
A level knob
A pan knob
A gate in
An env out
4 mods
stereo in/out 

Could even do 2 versions (or have a right menu setting for 4 stage envelope type)
ADSR
DAHD (Delay, Attack, Hold, Decay) for drums - the delay can be used for pushing drum hits slightly off grid.

and we can put options in the gutter

I don' want to delay the first library submission any more but immediately after that submission get to work on this and tree monster output.

**Comment by Torinbob** [comment]
Dropping this updated version here for reference:

<img width="860" alt="Screenshot 2022-11-08 at 22 34 55" src="https://user-images.githubusercontent.com/41232273/200694215-96310d57-f0e3-457c-ac4f-b25fce2d0810.png">

**Comment by Andreya-Autumn** [comment]
There aren't many stereo VCA's, ZZC has one with a soft clipper and Befaco has one with an EQ. This would fill a different niche since neither has an EG. I think this one's gonna be a banger. <3

**Comment by rubyglow** [comment]
> Dropping this updated version here

I like that one! Features I would love for this module, in the context menu, so without modifying the panel:

- A slider for changing the response curves/slope-control of the envelope, on a continum of log-linear-exponential. Even better if it could be such a slider for each of the attack, decay and release segments. I have found that it makes a dramatic impact on sound and is highly musically useful.

- 2 or 3 different modes to choose from, of re-trigger strategies. There's a spectrum of options here and they make quite a difference musically.

These features all together would (surprisingly) make it a rare and great envelope generator in Rack and would for sure become my favored EG+VCA combo.

**Comment by Torinbob** [comment]
@rubyglow

re - your first point - we would be following the way Envelopes work in the Surge VST. For each EG type (ADSR, DAHD) there are Analog and Digital versions. Analog has fixed curves, but Digital has 3 different curves you can select per segment (that's what those dots are for on envelope shapes in the visual).

I expect we can probably offer some re-trigger options - let us know what you'd like to see.

**Comment by rubyglow** [comment]
Sounds good. I'll get back about the re-trigger options....
What are the basic differences between analog and digital versions?

**Comment by baconpaul** [comment]
Digital is lines between the points either as lines, line squared, or sqrt line basically. The envelopes that digital synths in late 80s to earky 90s had

analog is an rc charge and discharge model which is snappier. The one in surge is actually a bit wrong so fixing it would be a step here and when we do we can think about different slopes and factors in the circuit I’m sure

**Comment by baconpaul** [comment]
Oh and we have a couple of retrigger modes in the adsr in surge already (basicalky retrigger from zero or retrigger from current) and would Cary those over with the retrigger from current being most likely default. Making this work on lfoeg is the one big bug left before 1.0 actually!

**Comment by audinf** [comment]
This is great. When can we try a beta version of it?

**Comment by baconpaul** [comment]
definitely not before i start writing it :)

**Comment by Torinbob** [comment]
Yes haha - the new module designs I'm posting here are only at the drawing board stage currently, but now that the initial release has been submitted to the library, hopefully Paul will have some time to start looking at them soon.

**Comment by baconpaul** [comment]
I’ve already started a next branch while I wait for the library machine to turn

my guess is January or so

**Comment by audinf** [comment]
> I’ve already started a next branch while I wait for the library machine to turn
> 
> my guess is January or so

That's wonderful :-)

**Comment by baconpaul** [comment]
> This is great. When can we try a beta version of it?

Next nightly has what I think is a complete egxvca

headed to library next week or so i bet, unless folks find big bugs in final testing.
