### ISSUE TITLE
Envelope generator can produce soft clicks when using DEFORM modulation

### ISSUE THREAD

**Issue by Rcomian** [surge-synthesizer/surge-rack#607]
Related to #541

![image](https://user-images.githubusercontent.com/684678/200910430-1c92d60d-0591-4e6b-8f65-c5548b806df6.png)

When using the LFO x EG with the `LFOxEG` output and modulating the DEFORM parameter, the crossover point doesn't compensate for the change in wave shape and a soft click can be heard on notes that repeat faster than the release phase of the envelope.

The click is not as bad as with #541 and can be mitigated by use of the deform param, but it's not entirely maskable if you want to use that output in that way.

To be honest I'm not entirely sure of the best solution here, as a full fix could mean that the LFOxEG output gets out of phase with the EG output and I'm not sure what kind of demons would spawn out of the resulting portal to hell.

The issue is worse with Deform Type 2 than it is with Deform Type 1. Deform Type 3 is not relevant since it just adds noise anyway.

I've attached an annoying minimal reproduction patch.

[click-repro.vcv.txt](https://github.com/surge-synthesizer/surge-rack/files/9974064/click-repro.vcv.txt)

**Comment by baconpaul** [comment]
oh i thought i got that all correct. I have a variety of compensations for deform in there but I must have a mistake. 

Thank you I'll take a look.

**Comment by baconpaul** [comment]
ahh and you don't need to modulate the deform you can just set it to extrema and it stays constant and you see the problem. (I thought the problem might be a changing deform but it isn't).

Sorry  I really thought I got this but i see what my test patch missed. Will take a look.

**Comment by baconpaul** [comment]
yeah you have identified why this is tricky. We either have to have (1) LFO discontinuous, (2) EG discontinuous or (3) LFOxEG != LFO times EG. Since the deform modifies the LFO and not the EG, and I am keeping the EG continuous you see what you see.

I think (and am working on but the math made my head hurt a bit) I can back out the deform from the LFO phase properly so that I can have all 3 continuous and just break the constraint that LFOxEG = LFO times EG, but only broken in envelope mode with deform non-zero.

Its just very fiddly math in one pretty sensitive spot of the surge modulator so want to be careful

i'll get this fixed before i submit to library though, I hope.

**Comment by baconpaul** [comment]
And thank you for the diligent bug reports. Super duper useful.

**Comment by baconpaul** [comment]
OK this was just unsolvable analytically

what i've done is add an optional low pass filter on the underlying envelope signal and added an envelope smoothing menu to the LFO. This *only* applies to the envelope setting and only if you are in retrigger from last mode

With that one pole activated at various settings, I can tame the click in your patch.

I chose a light but non-zero setting as the default.

**Comment by baconpaul** [comment]
oh and it will take a bit before that's in a nightly. later today though.

**Comment by Rcomian** [comment]
Yep, honestly I think that's probably the only way to go, i don't know if you can only apply the lpf on the transition or do a cross fade , but i'd agree there's no "proper" solution here.
Thanks for looking.

**Comment by baconpaul** [comment]
The envelope is slow enough that the lpf doesn’t really hurt and I turn it off for all the other types so I think it is fine especially since you can deactivate it

thanks for flagging it thoigh. Good changes!
