### ISSUE TITLE
A "Voice" expander

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#612]
This is an idea we've alluded to a couple of times on the community thread.

Imagine a voice expander which sidles up next to a VCO and adds

1. An ADSR envelope with a gate
2. Modulatable drift and gain
3. An optional filter, including simple LP/HP and more complex versions perhaps (which could be useful for the VCOs without a lo/hi cut on them).

That sort of thing.

**Comment by ContemporaryInsanity** [comment]
Is the need for this negated by auto-patch?

**Comment by baconpaul** [comment]
Yes
