### ISSUE TITLE
New Module - Quad LFO

### ISSUE THREAD

**Issue by Torinbob** [surge-synthesizer/surge-rack#620]
# BaconPaul Edit: The current todo list for this module at head

- [x] Changing name of  'Trig' input jack to 'Reset'
- [x]  In waveform menu, rename ramps to "Ramp Up' and 'Ramp Down'
- [ ] Synced timing notation/naming - can it be simplified/clearer?
     - [x] for example remove 'nt' so Just 1/4 rather than 1/4 nt
     - [ ] ~~Can we call Whole Note '1 bar' instead etc~~
     - [x] See ShapeMaster synced timing names for examples which I think are clearer/simpler to understand
     - [x] Slowest time is 16 whole notes (16 bars?) - could we maybe go slower to 64 or 128 bars?
     - [x] Fastest is 1/512 which seems super fast - 1/128 maybe fast enough?
     - [x] Can Timing at bottom of display have clickable drop down for synced timings so we can see them all perhaps?
- [ ] Modulate rate ratio in sync mode (desired behavior is to keep the snaps)

-------

# Original Message

After watching Omri's video, and seeing him feed the Mod Matrix module with multiple Bogaudio LLFOs, it made me think we should probably do a Quad LFO that would pair well with it as a modulation source.

It would be cool to have 3 modes for it I reckon:

Mode 1: 4 Independent LFOs (unsynced only)

Mode 2: 4 related LFOs that share the same frequency (that of LFO 1) but different phase - 90, 180, 270 degrees by default, but the phase of channels 2-4 can be set freely (LFO 1 can run unsynced or synced)

Mode 3: 4 related LFOs where LFOs 2-4 have a frequency that is either a mult or div of the freq of LFO 1. (LFO 1 can run unsynced or synced)

Depending on the mode, the labelling of Knobs and jacks changes. Something like this:

<img width="1268" alt="Screenshot 2022-11-11 at 19 56 38" src="https://user-images.githubusercontent.com/41232273/201425412-f5f36e78-eeb4-46ee-abcf-f3e79acf0907.png">

If the wave shape icons are drawn in code, we could show the effect of Deform on the wave shape.

Waveform menu (for selecting wave shape per channel) would also include settings for Range, Offset, Scale (Amp) and Smoothing.

**Comment by baconpaul** [comment]
So what's the form of "spread"? Is it that oscillator N gets base + spread * N in appropriate units?

Clever idea.

Those N/As in modes 2-4 seem like they are screaming out for something.

**Comment by Torinbob** [comment]
I'd want to check with Pyer but in essence yes, I think that's the form.

But perhaps we'd want to tweak the '+ spread * N' part such that Oscillator 2 didn't always get the minimum amount of spread for each of the four controls and Oscillator 4 didn't always the maximum for each. Maybe not though - up for discussion :)

**Comment by baconpaul** [comment]
So here’s a question 
What would a 2- or 4 dahdsr look like?
Probably a separate module tho

**Comment by Torinbob** [comment]
Well, I already have an idea for a separate 4 x AD

And we could do a dual ADSR / DAHD maybe (like on the EGxVCA)? Splitting them into two modes of 4 sliders like that makes it easier to fit in than the full set of 6 sliders – am I right in thinking those combinations would be used together most?

For example I don't really see the need to have both hold AND sustain in the same envelope - I would be using one or the other depending on whether it was being used with a trigger or a gate - but I might well be missing something.

**Comment by baconpaul** [comment]
Oh is 4xAD in the list already? I'm sorry! That would be perfect.

I'll tag you on discord for the post that made me think of this.

**Comment by Torinbob** [comment]
haha yes - having seen that grab on Discord a 4 x SD would certainly have been of use there!

I'll create an issue for the 4X AD module.

**Comment by audinf** [comment]
Another great addition to the current list of modules. Not as desperately needed as the VCAxEG but still something I am very keen to have.
