### ISSUE TITLE
Surge Rotary doesn't initialize Doppler and Trem knobs to default values upon inserting them to your Rack

### ISSUE THREAD

**Issue by pgatt** [surge-synthesizer/surge-rack#639]
Knobs are zeroed upon instantiation, whereas double clicking them to "initalize" them take them back to the values I expected from previous versions of Surge Rotary. Didn't check deeply whether this affects other knobs or other modules.

**Comment by baconpaul** [comment]
The reason for this is that the "Init" preset is different than "internal default values for all the knobs" and, in presence of an init preset, that wins on load. "Init" is just a preset with a name and nothing constrains it to be the internal state.

I meed to think about what to do about that, if anything. Thank you for the report.
