### ISSUE TITLE
Cosmetic concerning Filter module (for Rack v2)

### ISSUE THREAD

**Issue by DomiKamu** [surge-synthesizer/surge-rack#643]
Hi,

It's just a "cosmetic" issue, not critical.

When I open the modules browser, for this module it's indicated Filters (into amber module screen) : 

![image](https://user-images.githubusercontent.com/24851960/202628895-d0c7f7ef-6ab0-49cf-896b-cd06cfb944b7.png)

... instead of **Filter** (without plural).

Thanks for your modules, they're excellent! 🥇

**Comment by baconpaul** [comment]
Thanks!
