### ISSUE TITLE
String VCO Memory Leak

### ISSUE THREAD

**Issue by DanGarman** [surge-synthesizer/surge-rack#653]
Running String VCO produces a steady increase in memory use, suggesting a memory leak. Great module, btw.

**Comment by baconpaul** [comment]
Thanks I’ll look

tge string memory model is tricky to avoid audio thread allocations of the delay line so it definitely has a memory-doesn’t-drop character but it recycled unused lines. If you have a patch that would help

**Comment by baconpaul** [comment]
Awww damnit I see what’s happening 

thank you very much for this report. I’ll work on a fix and keep you posted.

**Comment by baconpaul** [comment]
OK I have this fixed and we are going to include it in our first library release. It should also be in a nightly tonight.

Thank you very much.

**Comment by DanGarman** [comment]
Appreciate your work, glad I could help by reporting it in beta

**Comment by baconpaul** [comment]
yeah just under the wire! Super useful. Enjoy making music with surge :)
