### ISSUE TITLE
LFO x EG panel background gradient

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#654]
Appears different to other modules.

**Comment by baconpaul** [comment]
Which skin?

**Comment by ContemporaryInsanity** [comment]
Dark.

**Comment by baconpaul** [comment]
OK thanks! @Torinbob - can you take a peek wyham?

**Comment by Torinbob** [comment]
Looks the same to me (see grab).

And technically I can't think of any reason why it would/could look different as all the 12hp modules share the same background panel (within each theme at least)

<img width="1017" alt="Screenshot 2022-11-25 at 17 19 16" src="https://user-images.githubusercontent.com/41232273/204032402-80e4358d-22c9-4ea4-90de-b303496d3829.png">

**Comment by ContemporaryInsanity** [comment]
![image](https://user-images.githubusercontent.com/12547379/204032600-c98f1d57-695f-449d-b82b-79fb204c56c4.png)

**Comment by Torinbob** [comment]
Huh - looks like it is LFO x EG that is wrong.
