### ISSUE TITLE
Clock Handling in Widget classes re-use

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#665]
1: use the pattern that the module defines typedef clock_t
2: Take the json and the menu stuff and move it to a helper class in XTModule and XTModuleWidget respectively
3: Refactor to use that consistently

**Comment by cosinekitty** [comment]
Watch out for the name `clock_t`. It is a standard type name: 
https://en.cppreference.com/w/c/chrono/clock_t

**Comment by baconpaul** [comment]
Oh ha yeah thanks I would have found that out the hard way
