### ISSUE TITLE
radio buttons don't work when module positions are locked

### ISSUE THREAD

**Issue by jpnielsen** [surge-synthesizer/surge-rack#676]
Surge XT 2.0.3.0, Windows 11, Rack 2.2.0

lock module positions in the rack view menu and the surge radio buttons do not work. All modules have the same problem.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/27916597/204647644-fc7c79df-4fcb-4eb6-899b-7df49b0402e3.png">

<img width="528" alt="image" src="https://user-images.githubusercontent.com/27916597/204647754-0f8f82ce-ebd0-466c-8857-39a9b3a00aa1.png">
Whole module just turns red when a button is activated.

**Comment by baconpaul** [comment]
Oh wow I didn’t even know that feature was there

thanks I’ll take a look

**Comment by baconpaul** [comment]
OK so here's how it seems to work

Other modules turn red when you click on a background or something
Surge does the same when you click on a knob etc

so my custom modulation buttons must not be consuming some event which makes the lock-turn-red later.

Thanks for the report @jpnielsen - I can repro and have a pretty good idea what it is.

**Comment by jpnielsen** [comment]
the modules normally turn red, when I box-select them.

**Comment by baconpaul** [comment]
It seems in lock mode any module turns red when you don’t hit a xontrol. Or at least the two non surge ones i tried did. Pull up fundamental lfo in lock mode and click the background and it turns red 

the problem here I think is that the mod arm button which is a custom widget is not consuming some event so rack thinks you are doing a background click. At least that’s my current theory

**Comment by baconpaul** [comment]
Yeah that's exactly what it was. I was not consuming an event in one place.

I have a fix to this I'll merge tonight so the 2.1 beta (downloadable here) will be corrected. Depending on how many small bug reports we get now we are in the library we may also do a 2.0.4.0 before christmas time and if we do i would sweep this in too.

Thanks for the report!
