### ISSUE TITLE
Presets: Do we want them?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#68]
Surge has presets which set things into nice states and move the knobs.
Rack has a bit of a "can't move knobs from behind the panel" mindset
But that is skeuomorphic bias. We can, of course, move the knobs.

So I think we probably want presets for the effects and oscillators and stuff, and have those just move then knobs when you select them.

we need to put those presets somewhere. But that's doable.

start with SurgeFX and SurgeOSC.

**Comment by baconpaul** [comment]
Of course, the first example of preset is "init state" when you switch control types.

**Comment by tank-trax** [comment]
something similar on FM2 (fixed) for M1 Ratio on surge-rack OSC

its init setting is 1056964608

**Comment by baconpaul** [comment]
Yeah I see all of those. It's me not doing something in the init sequence properly. Should be straight forward to fix when I add init types. (I think the problem is when a value changes from float to int and the .i isn't reset; so having inits will solve it)

**Comment by baconpaul** [comment]
So this is only a pain because of the startup path. I want to make sure if I have saved a patch that when I create a module it doesn't clobber that. In surge v1 if I cal param.setValue() the knobs move so I can do preset mapping. Just tedious and fiddly so not today.
