### ISSUE TITLE
New Module - Surge XT Patch Player

### ISSUE THREAD

**Issue by milkowski** [surge-synthesizer/surge-rack#681]
It would be great to bring back the Surge Patch Player module that was present in previous Surge for Rack edition.

**Comment by baconpaul** [comment]
There’s some technical reasons why we didn’t do this (and that would make it hard but not impossible in xt) but also a bit surprised - what was it about the module you liked? It seems “play an entire patch” is better handled via surge xt running in host no?

**Comment by milkowski** [comment]
Yes, host is a paid option or using Cardinal but curious what makes it difficult in Surge XT. Maybe I could help somehow in my spare time, because having dedicated module is really more convenient way in case there are more than one instance of it.

**Comment by baconpaul** [comment]
The things that make it difficult are 

1: we don’t (and can’t) build every surge xt feature in the rack toolchain so some parts of the engine are missing. At this point it’s only the formula modulator but you would have to fail to load those patches, although I also just turned off the airwindows submodule build and we would have to turn that back on 

2: shipping all the patches would make the binary huger still and so we would really need a strategy 

3: ui etc - the design exercise is real work as is the coding 

4: most patches don’t have macros assigned and so don’t have robust modulation targets and absent the ui being available (which it wouldn’t be in rack) there’s no way for a user to fix that 

all these made us conclude that the patch player would be quite a lot of work for a sub par experience, and host only costs 30 bucks, so we didn’t add it basicalky.

**Comment by milkowski** [comment]
I look into old Surge Rack Path Player UI and I agree porting full capabilities of VST plugin along with standard patch set is pointless and is well server by VST host module.

What I meant initially was a module capable of playing loaded patch or patch directory with custom patch files prepared for use with that player by user. No default patch set would be provided by the module itself and assigning possible 8 macros for CV inputs would be a task left for the user.
So the player UI would be similar to the previous one except the path browser would be empty by default and proper files/directory need to be loaded manually (possible patch selection then could be CV controlled by great Surge Rack XT invention of mod controllers and also macro inputs with their own possible rotary controllers next to CV would take it to the another level of awesomeness).

Answering your points:

1. Not sure how difficult is to enable full functionality with LUA scripts, but initially, if those patches are customized anyway, there could be restriction only for patches w/o them.
2. There will be no patches shipped with the module
3. The UI will be similar to the existing one with additional patch set load functionality and possible (but not necessary) additional visualizations like VU meter/scope macro indicator or so (I would stick to the existing convention where all chosen patch information including name/category and visualizations will be shown on one general module display).
4. Only proper user patches with proper macro assignments will be supported.

Is it reasonable proposition?

**Comment by baconpaul** [comment]
Yeah if we just read patches from the user area (so you model them in the standalone) and fault out if you use Lua that certainly addresses some concerns 

lemme think about it and chat with the team. Appreciate you engaging here also

**Comment by mkruselj** [comment]
I don't see the point of this if it would not support loading the great majority of patches that are available out there.

**Comment by baconpaul** [comment]
Yeah I think this is the wrong module for our collection I agree. Host exists and works well. I'm going to close this as a 'wont do' for all the reasons listed above.
