### ISSUE TITLE
Bar Editor gestures and details still to go

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#683]
The rewrite of the LFO and Alias step editors makes things way way better but theres some stragglers i didn't get to

- [ ] Tuning quantization gesture
- [ ] line draw gesture (maybe but also maybe don't bother)
- [x] Menu set to default vs zero
- [x] Alias and LFO gets 'presets' in the RMB (maybe?)
- [x] Alias renames 'Step' to 'Harmonic'

**Comment by ContemporaryInsanity** [comment]
Just grabbed the latest, fantastic stuff!

One thing, so far at least, can you exclude LFOxEG Type from randomisation please?

**Comment by baconpaul** [comment]
Oh yeah that’s a good idea!
