### ISSUE TITLE
Modulation range type-ins out of range

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge-rack#698]
**VCV Rack Pro 2.2.0, Windows 10, REAPER**

**1. Combulator Center | V/Oct Modulation** 

When trying to type-in values, after clicking enter, they exceed the expected value range. 

For example, when RMB clicking on the Center control, then typing in 261.63 Hz, upon clicking enter, the resulting value in the field is +49913.80.

![image](https://user-images.githubusercontent.com/81161256/205509887-f266c767-5089-489d-bb4a-6014447d4979.png)

**2. LFO x EG | V/Oct Modulation**

Same as above, when trying to RMB click and type-in 1000% into the Rate modulation field, the resulting value is 1600%.

![image](https://user-images.githubusercontent.com/81161256/205510216-0559fdbc-f1a1-4973-b522-ddc66b0b9486.png)

**3. Holding CTRL for fine adjustments to knob parameters seems too coarse for making precise settings.**

When manually setting the range with the mouse while holding control, 261.39 Hz is about as close as one can get to the desired setting of 261.626 Hz.

![image](https://user-images.githubusercontent.com/81161256/205510381-5fb15d6d-7040-4150-9f35-e2bf5c0c0444.png)

**Comment by baconpaul** [comment]
Thanks will look this week

**Comment by baconpaul** [comment]
Ok…. Next week!
