### ISSUE TITLE
Surge XT Twist VCO crashes RackPro 2.2.1

### ISSUE THREAD

**Issue by technochitlin** [surge-synthesizer/surge-rack#721]
Surge XT Twist VCO crashes RackPro 2.2.1. I can reliably repeat this on my Win10 Pro machine by loading in Twist and clicking on any Mod button, then touching or adjusting a knob.

**Comment by baconpaul** [comment]
Which version of surge xt are you running please?

**Comment by baconpaul** [comment]
(I ask because we fixed this problem between the last beta and 2.3.0)

**Comment by technochitlin** [comment]
Aha! Deleted SurgeXT out of my plugins (it was still the beta) and reloaded the modules. Problem solved. Apparently the beta didn’t know to update for some reason.

 �

Cheers,

James

 �

**Comment by baconpaul** [comment]
Yeah the beta has a version ahead of the library (it is 21 beta vs 203) but there was a while where 21 beta had the bug as did 202 and so on... you know

Anyway thanks for reporting and have fun making music with surge! I'll close this issue.
