### ISSUE TITLE
INIT settings and display anomalies 

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge-rack#74]
when the presets knob is turned from right and then back to left the settings display a numerical value of -2147483648 for Uni Count whereas it should be a range between 1 and 16

once the orange knob for Uni Count is moved the display reverts back to displaying the 1 and highest value 16

this will repeat whenever the presets knob changes from to Classic from Sine

as well, many settings made with the orange knobs display values inconsistent with the knob position or will change when moving the presets knob right and left

![SurgeOSC 01](https://user-images.githubusercontent.com/41337033/57201354-f12aba00-6f65-11e9-91f8-59ec1eae970b.gif)

**Comment by baconpaul** [comment]
Also related to #68

**Comment by baconpaul** [comment]
I just fixed this mis-display in OSC with my redraw of it; I'm going to close this issue and let init and preset conversation carry on in #68 along with my sweep of the OSC code. Thanks!

**Comment by baconpaul** [comment]
OK I have this finally fixed with a push coming in one minute
