### ISSUE TITLE
Decay of Twist's LPG short 

### ISSUE THREAD

**Issue by Setkias** [surge-synthesizer/surge-rack#766]
Compared to Macro Oscillator 2 the LPG of Twist only produces very short decay times.

**Comment by baconpaul** [comment]
This has always flummoxed me as to what the api is. We had it wrong in surge for the longest time also. Thank you - I will look

**Comment by baconpaul** [comment]
Hmm yeah ok I confirm I get a totally different result than MacroOsc2. 

Let me compare the code. We are calling the same underlying thing. I must be using the API improperly somewhere.

**Comment by baconpaul** [comment]
Yeah OK I have a fix to this one also which should be in a nightly later today. Thank you.

I don't know why I didn't think to do that comparison myself, but I really appreciate both these bug reports.

**Comment by Setkias** [comment]
Thanks for the swift fixes!
Back to patching.
