### ISSUE TITLE
Twist's does not reset on single-process sample rate change. 

### ISSUE THREAD

**Issue by Setkias** [surge-synthesizer/surge-rack#767]
Selecting a higher sample rate outputs a higher pitch.

**Comment by baconpaul** [comment]
I wonder if I forget to reset it. I bet that’s it 

If you change sample rate and create a new twist does it work?

**Comment by baconpaul** [comment]
yeah that's it. run a twist, change 44.1 -> 48, pitch changes, with that running bring in a new twist and it is in tune.

There must be a reset I am skipping. Let me look right now. thanks. Great bug report!

**Comment by baconpaul** [comment]
OK yeah thanks. It will be fixed in the next nightly and also in the upcoming 2.1 release.
