### ISSUE TITLE
0eb8516 crashes rack when module browser sorted by last updated - linux

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#771]
[12.528 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
40: ./Rack() [0x403f5d]
39: /lib/x86_64-linux-gnu/libc.so.6(+0x42520)
38: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0xf30de)
37: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x159)
36: ./libRack.so(rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int)+0xc7)
35: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x159)
34: ./libRack.so(rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int)+0xc7)
33: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
32: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
31: ./libRack.so(rack::widget::FramebufferWidget::drawFramebuffer()+0xc2)
30: ./libRack.so(rack::widget::FramebufferWidget::render(rack::math::Vec, rack::math::Vec, rack::math::Rect)+0x39f)
29: ./libRack.so(rack::widget::FramebufferWidget::draw(rack::widget::Widget::DrawArgs const&)+0x44a)
28: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
27: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
26: ./libRack.so(rack::widget::ZoomWidget::draw(rack::widget::Widget::DrawArgs const&)+0x4c)
25: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
24: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
23: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
22: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
21: ./libRack.so(rack::app::browser::ModelBox::draw(rack::widget::Widget::DrawArgs const&)+0x15a)
20: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
19: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
18: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
17: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
16: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
15: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
14: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
13: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
12: ./libRack.so(rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&)+0x34)
11: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
10: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
9: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
8: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
7: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
6: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
5: ./libRack.so(rack::window::Window::step()+0x74c)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xa0f)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)
0: ./Rack() [0x403e89]

**Comment by baconpaul** [comment]
Ooooh that’s odd. Let me look this morning, thank you as always

**Comment by baconpaul** [comment]
Duh sorry about that. It will be fixed in next nightly. (I shuffled code after testing this and that was a mistake obvs)
