### ISSUE TITLE
Twist's LPG has no attack stage

### ISSUE THREAD

**Issue by Setkias** [surge-synthesizer/surge-rack#773]
Twist's built in LPG is causing audible clicks. It looks like there's no smooth attack stage.
[twist_lpg.zip](https://github.com/surge-synthesizer/surge-rack/files/10328516/twist_lpg.zip)

**Comment by baconpaul** [comment]
Oh right now I fixed it the difference between the surge and rack voice model will matter. I have some ideas and will look this week - def fix for 2.1

thank you

**Comment by baconpaul** [comment]
Yeah that was it; there was a voice-start which was happening when the LPG was struck which was not correct for the rack usage (but is correct for the surge vst; even though the delay calculation is wrong there too).

Should be fixed in nightly later tonight. Hour from now or so. Thanks again.
