### ISSUE TITLE
LFO x EG Trig A and B

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#776]
Module LFOxEG V 2.0.3.0
Hi, I'm just doodling with this module to understand it. But I see that the 2 Trigs A and B fire at the same time at the start of a step. They're the blue and green trace in the oscilloscope. I was under the understanding that Trig B fires at the end of the step.

Bug?

![image](https://user-images.githubusercontent.com/14888092/210189970-a3dcaf4c-ae2f-4f06-bb03-5d3e9ccc8edb.png)

**Comment by baconpaul** [comment]
They both fire at the start of the step. They are just two independent sets of set table triggers. 

So no bug unless the manual says b fires at end

**Comment by therealkitman** [comment]
Thanks for the clarification. I'm not sure what the manual says as the only ref I can find [this](https://surge-synthesizer.github.io/rack_xt_manual/#the-surge-lfoxeg-module) which is a bit sparse. 

Is there a more detailed manual for the VCV Rack version?

**Comment by baconpaul** [comment]
No; the vst has a complete manual but the rack manual is relatively bare bones. But we are an open contribution volunteer driven project if you would enjoy joining the team to help with that!

**Comment by therealkitman** [comment]
> But we are an open contribution volunteer driven project if you would enjoy joining the team to help with that!

Hm......thinking. Let's chat.

**Comment by baconpaul** [comment]
Sure! The manual is just a document managed in GitHub and authored in markdown. You can find it here https://github.com/surge-synthesizer/surge-synthesizer.github.io/tree/master/rack_xt_manual

the rack discord probably the best place to chat, but here works also as does rack community
