### ISSUE TITLE
Rack crashes when adding String VCO.  db0ef67 linux.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#810]
[8.489 info src/app/Browser.cpp:89 chooseModel] Creating module Surge XT String VCO
[8.490 info /__w/surge-rack/surge-rack/src/XTModule.h:69 showBuildInfo] [SurgeXTRack] Instance: Module=VCO<String> BuildInfo=os:linux pluggit:SURGE_RACK_PLUG_VERSION surgegit:SURGE_RACK_SURGE_VERSION buildtime=Jan 13 2023 13:53:54
[8.532 info src/app/Browser.cpp:93 chooseModel] Creating module widget Surge XT String VCO
[8.542 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
21: ./Rack() [0x403f5d]
20: /lib/x86_64-linux-gnu/libc.so.6(+0x42520)
19: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x3d96d2)
18: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x53d9b1)
17: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x53e47d)
16: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x342049)
15: /home/ewen/.Rack2/plugins/SurgeXTRack/plugin.so(+0x3430e0)
14: ./libRack.so(rack::widget::Widget::step()+0x36)
13: ./libRack.so(rack::widget::Widget::step()+0x36)
12: ./libRack.so(rack::widget::Widget::step()+0x36)
11: ./libRack.so(rack::widget::Widget::step()+0x36)
10: ./libRack.so(rack::widget::Widget::step()+0x36)
9: ./libRack.so(rack::widget::Widget::step()+0x36)
8: ./libRack.so(rack::ui::ScrollWidget::step()+0x13)
7: ./libRack.so(rack::app::RackScrollWidget::step()+0x36f)
6: ./libRack.so(rack::widget::Widget::step()+0x36)
5: ./libRack.so(rack::window::Window::step()+0x388)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xa0f)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)
0: ./Rack() [0x403e89]

**Comment by baconpaul** [comment]
Thanks - every time or sporadic?

**Comment by ContemporaryInsanity** [comment]
Three times in a row on first attempt, just tried again and it worked, so good luck!

**Comment by baconpaul** [comment]
Ugh
Thank you

**Comment by baconpaul** [comment]
So I can't reproduce this. When I run rack under valgrind i see no memory errors. When I run under asan i see no memory errors.

Are you sure that you didn't have some half-way install state when you upgraded? Does it ever crash for you now?

I'm not quite sure what to do here. I'll keep poking a bit but would be curious if this happened again post upgrade?

**Comment by ContemporaryInsanity** [comment]
Certain.

Hasn't happened since, yet.

I'll keep it in mind too and create string VCO's more often than I might otherwise.

**Comment by baconpaul** [comment]
wow tough. I also reviewed the VCO diffs and don't see much. Just some stuff which isn't even on for string.

Any other VCO crash? Do you have an odd or very high sample rate like 192khz or something?

**Comment by ContemporaryInsanity** [comment]
No other crashes so far.
48k.

**Comment by baconpaul** [comment]
OK

so valgrind shows nothing; the code review shows nothing. let me try my mac sanitizer tools as a last gasp.

i hate bugs like this. there's so many things it could be. and none of them are obvious (or even in the surge code in some cases). Thanks for the report!

**Comment by ContemporaryInsanity** [comment]
I do have a module in development that adjusts other modules which has known faults, though they typically result in my module crashing as opposed to the one it controls, so could be related to that, however those crashes are generally repeatable, this one less so.  I wouldn't put too much more effort into it if I were you but I'll keep an eye out for it.

**Comment by baconpaul** [comment]
OK. I'll take another poke tomorrow but if asan on mac is also clean I'll go ahead and do the library submit.

Thanks as always for all your help

**Comment by ContemporaryInsanity** [comment]
Think we can close this now, I've got through a whole truck load of String VCOs since and it's been fine.

**Comment by baconpaul** [comment]
OK thanks! Wonder what it was. But appreciate the report

Turns out debugging it I found a separate memory issue with json in surge (which will be fixed in 2.1.1 soon) but also i think in rack proper! So it was worthwhile checking even if it wasn't reproducible.
