### ISSUE TITLE
Classic OSC .. has no Unison Voice activity 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge-rack#82]
"UNI Spread" and "UNI Count" currently innactive

**Comment by baconpaul** [comment]
Yeah as we said on slack this is per voice. gotta fix that....

**Comment by sense-amr** [comment]
yeh it wont work in this context.. unless i guess its triggered on GATE?

**Comment by baconpaul** [comment]
Just fixed this. Basically I do the equiv of a voice retriever when you change the param. A bit specific but works well
