### ISSUE TITLE
EG x VCA display modification

### ISSUE THREAD

**Issue by firolightfog** [surge-synthesizer/surge-rack#821]
I'd like to propose a change in the display to have the level over the Level knob and the envelope shape above the envelope sliders.

I'm sure that it looks like a minor change but I believe ergonomically it would be an important one. 

![image](https://user-images.githubusercontent.com/34127628/215257942-9a8952c8-9669-498a-8587-96f4bc9c51ce.png)

I feel kind of bad knowing the lengthy alpha and beta testing periods and the amount of coding it may require but I've only started to use this module now...

Best regards, Andras

**Comment by baconpaul** [comment]
Well it’s an easy code change but I’m not sure. Let me defer to pyer and Steve on this one.

**Comment by ContemporaryInsanity** [comment]
Does make ergonomic sense.

**Comment by baconpaul** [comment]
The reason I’m not sure: When editing it aligns things; when looking at the signal flow it is backwards. So Inout to output is left to right input hits adsr hits levels.

**Comment by ContemporaryInsanity** [comment]
Leave display as is, swap VCA & env controls?

**Comment by baconpaul** [comment]
Oh ha yeah that is a way better solution

**Comment by baconpaul** [comment]
Yeah ok I need to do a 2.1.1 anyway for a couple of other things I will swap the controls (turns out steve had the same conclusion independently!) for that release 

will close this issue when the code and nightly are updated

**Comment by baconpaul** [comment]
<img width="325" alt="Screen Shot 2023-01-28 at 8 39 53 AM" src="https://user-images.githubusercontent.com/13387561/215269695-acdc3a3e-173a-4ba4-808d-ab5ecaa8089b.png">

Here's the panel in the nightly later this morning and which will be in 2.1.1

**Comment by baconpaul** [comment]
oh and: it is way better! Thanks for saying something :)
