### ISSUE TITLE
Option to prevent Surge XT directory from being generated under Documents in Windows

### ISSUE THREAD

**Issue by GBaige** [surge-synthesizer/surge-rack#831]

**Comment by baconpaul** [comment]
Which version are you running? I thought I added this feature in 2.1.0

**Comment by baconpaul** [comment]
yeah 2.1.0 should not create this directory if you run only rack. Can you please give more details?

**Comment by GBaige** [comment]
I'm using Cardinal VST3 version 22.12

**Comment by baconpaul** [comment]
Ok. Well if cardinal upgrades from surge 2.0.3 to 2.1.1 then the problem will get solved. I can’t do that so closing this issue since it is fixed here.

Thanks!
