### ISSUE TITLE
EGxVCA - Polyphonic behaviour

### ISSUE THREAD

**Issue by rubyglow** [surge-synthesizer/surge-rack#838]
Hello Paul/Surge team

I had my first serious play with EGxVCA yesterday and thoroughly enjoyed it. Interestingly I particularly enjoyed the analog mode. I think this now takes over the duties I have used Vult Spank and Slap for until now. Very nice module, thanks!

So, I made a polyphonic patch with it and it works fine. However - I have one nit, one bit of somewhat unobvious nuisance that I would love for you to fix. It concerns the polyphonic behaviour of the gate input in relation to the inputs.

I had 4 note polyphony on the inputs and I applied a monophonic gate to the gate input, which I naively thought would do the intuitively right thing, but instead I discovered that the gate would only gate the first channel of the poly input, and the 3 remaining would be mute. So I had to use an external module to clone the poly gate signal, so that all 4 channels would be gated.

You can see the simple patch in question here: https://www.youtube.com/watch?v=9kDe04ae-pg

In a strict technical (developer) sense this might be correct, but for a user and a player I don't think it is. I think the simple and logical expected behaviour would be, that if a mono gate is presented, it should apply to all poly input channels, and I cannot see any downsides to this scheme. I'm totally onboard with the fact, that if, say, 2 or 3 gate channels are presented you shouldn't start to mux those out in some crazy scheme to the poly inputs, that's not needed at all, and no player would do that. But the poly input and mono gate scenario I think is so common, obvious and straight forward that I would emplore you to implement that, and thus further increase the joy of using the module.

Thanks for your consideration and for the wonderful Surge XT modules. They are rapidly becoming my defaults and go-to's.

All the best,
Lars

**Comment by baconpaul** [comment]
Yeah a mono gate should a panda to audio poly indeed. I’ll see if I van get this into 212 thanks!

**Comment by baconpaul** [comment]
Ok this should be fixed in the next nightly in about 30 minutes and I will include it in my 2.1.2 update this week 

thanks for saying something! That was a silly oversight when I wrote the circuit

**Comment by rubyglow** [comment]
Well thanks a bunch for the quick fix Paul! Yeah, I thought it might be a bug/oversight but you never know :-)

**Comment by baconpaul** [comment]
Ok submitted to library so closing this

**Comment by baconpaul** [comment]
This fix hit the library today
