### ISSUE TITLE
SurgeFX: Remove CV Gains; add MG module

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#84]
SO I’m thinking about a small design change which will take out one feature and replace it with another
After @sense and I were chatting I added “input cv gains” on each input on the delay. That is, the delay is param0 + gainknob + cv
these are distinct from the input and output gains in the blue section
So adding a gain knob to each CV control in our modules is going to be messy UI wise and mostly not used.
So I propose the following
1: I add a new module “MG” which is basically a vertical rack with as-many-as-I-can-fit flower knob input and output
2; That module basically lets you have a stack of surge gain modifiers and is narrow.
3: I take the gain knobs off the delay and compact the UI
The upshot is if you want a single LFO which puts all its intensidy on pan and half its intensity on depth on the delay you have to route it into the little micromixer
From looking at other rack modules this seems way way more idiomatic.
So I’m kinda gonna do it… but you know wanted to let you know first I guess?!

**Comment by Sense** [comment]
WTF ? Why did you mentioned me @baconpaul ?

**Comment by baconpaul** [comment]
Oh sorry @sense on slack is @sense-amr on GitHub and I copied from slack. Apologies!

**Comment by baconpaul** [comment]
Don't need an MG module since Fundamental has 8-vert
