### ISSUE TITLE
Wavetable and Window VCO's Morph Issue

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#841]
version 2.1.1.0
This may be just a cosmetic issue. If I manually Morph through a wavetable the current the 3D wave follows the correct wave number and is highlighted.

https://user-images.githubusercontent.com/14888092/218652465-85a4f3e6-3245-463e-a0dc-6d5f9009b500.mp4

But if I add an LFO through MOD1 to the table only the wave select by the initial Morph position is highlighted but follows the waves being passed through. Kind of confusing.

https://user-images.githubusercontent.com/14888092/218653692-f601cae2-6e20-4f3e-8320-164b0fc8e129.mp4

**Comment by baconpaul** [comment]
Oh ha right it looks like it uses the unmodulated knob for the z axis position but not for the wave. Thanks!

**Comment by baconpaul** [comment]
This fix hit the library today

**Comment by therealkitman** [comment]
Thanks Paul :+1: 

Very slight issue still and I'm sorry if I'm being pedantic - the Wavetable VCO grabs only the first frame of a One-Shot and sweeps it in the Z axis regardless when I send a Trigger during the sweep. The audio is ok though.

I'm assuming the waveform in the Window VCO  is changing during the sweep as it's being manipulated by the associated window shape.
Happy regardless if you want to reopen this issue or not.
https://user-images.githubusercontent.com/14888092/219990163-9c4829eb-63c7-4dee-a2d7-a2eca4e63ffd.mp4

**Comment by Petervos2018** [comment]
I think reset resets the start of the chosen wave within the wavetable , in order to reset the chosen wavetable you have to reset the modulator that is modulating the z axis. But I could be wrong.

**Comment by baconpaul** [comment]
The display is a separate oscillator than the audio and isn’t impacted by the trigger is the answer I thi k
