### ISSUE TITLE
Oneshot tail paint (was: Trigger/Reset Inputs on Wavetabel and Window VCOs)

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#843]
V. 2.1.1.0

I'm not sure what the Trigger/Reset inputs are meant to do on these two inputs. At first I thought if the wave was a OneShot the trigger would cause a single sweep through from the current wave frame to the end. Also I thought the reset would push the start to the first frame as set by the Morph position.

But in both cases nothing seems to happen. is there a problem or am I misunderstanding something?

https://user-images.githubusercontent.com/14888092/218961902-2f466563-8fa2-490a-bcab-85e9bae1f14b.mp4

**Comment by therealkitman** [comment]
BTW, I "THINK" I'm seeing something similar on the Surge standalone v 1.1.2 in regard to animated wavetables. But it's a bit hard to sort out as I rely on visual feedback of LFOs etc that the standalone lacks.

**Comment by baconpaul** [comment]
Here's how it works

The "reset" resets the oscillator. It's the same thing that happens at note on in the vst. It resets phases for unison, restarts the note drift, and a few other things. If you set unison to 2 and rmb to choose "phase from 0" you can see it in a scope.

For a few oscillators there are modes other than reset. String, Twist and Window/WT in one shot mode toggle from "reset" to "trig" to indicate that the init action restarts playback. On string it re-fills the burst buffer, on twist it re-triggers the LPG.

On window/wt in one shot mode it starts the one shot again.

None of these change the modulation or morph mode. So in one shot mode on a trigger the one shot playback will start at the snapped modulated value of morph when hit.

I'll leave this issue open so we can clean this up in the manual, but I hope that answers your question. It matches what I see when I run latest in rack here too, and matches what the code does.

**Comment by baconpaul** [comment]
https://surge-synthesizer.github.io/rack_xt_manual/#the-resettrigger-input-on-vcos I've added this comment to the manual in a slightly cleaned up form so will close this now. Please do chime in if something isn't clear.

**Comment by therealkitman** [comment]
Thanks Paul. The descriptions make sense to me now.
However - there seems to be an issue with the "Pulse - 1 shot". If you arrow left or right then come back to Pulse the last frame in the wavetable changes? Not an issue for me in my case but a bug none the less?

![image](https://user-images.githubusercontent.com/14888092/219261275-683d6e71-74e3-420f-bbab-235a6fee6b8c.png)

![image](https://user-images.githubusercontent.com/14888092/219262477-0521578f-99e9-496b-b6fe-b077ff46c7b9.png)

https://user-images.githubusercontent.com/14888092/219262296-d0a5a45d-6b9b-4a64-9d72-496f59e780a5.mp4

**Comment by baconpaul** [comment]
Oh I fixed that in surge vst but need to get the fix to rack. Lemme reopen this

**Comment by baconpaul** [comment]
An easy way to see this is to just alternate between blip3 and pulse in the wavetable viewer

**Comment by baconpaul** [comment]
and the surge vst3 doesn't have the corruption at the end; so i must have missed one trick in the port. (The corruption isn't in the audio either just the graphics)

**Comment by baconpaul** [comment]
grr maddening. why can't i find this this morning! Ahh well another day.
