### ISSUE TITLE
Mixer just with sliders

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#845]
Because sliders are sometimes what you want

**Comment by dustinlacewell** [comment]
Hopefully RMB

**Comment by baconpaul** [comment]
I’ll know when I write the code

I’m actually not sure which is better - seeing both in the browser might be smart

**Comment by baconpaul** [comment]
But if it is a separate module it is 95% the same code of course

**Comment by baconpaul** [comment]
I dont know why i wrote mod matrix here. This was supposed to be for the mixer. Obviously.
