### ISSUE TITLE
Twist VCO Waveforms

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#846]
V.2.1.1.0
This may just be a UI glitch as the audio seems ok. Using the Vowels/Speech engine as you scroll through with Segments the waveform is mostly flat until it hits certain vowels (eg Echo, Oscar and X-ray).

https://user-images.githubusercontent.com/14888092/219540256-9a53b3e1-c8e7-4ff0-b7a2-295f9635d783.mp4

**Comment by Andreya-Autumn** [comment]
Hmm, this only happens with the LPG active. And I see the same or similar behavior in the VST/AU. Without the LPG on, the display shows three cycles of the waveform, like most our oscs do. When the LPG comes on the 3 cycles are no longer drawn identically, and the difference I'm seeing doesn't make any sense. Probably a Surge bug from before the rack port I bet.

**Comment by baconpaul** [comment]
the display with the LPG is wonky yeah. The audio is correct but the delay doesn't 'trigger' the LPG at the start of the oscillator onset.

The LPG in rack got fixed in 2.1 but you are correct the display didn't. Hmm. Need to ponder. May be tricky

**Comment by baconpaul** [comment]
Pretty sure the right answer here is have the display oscillator (which is of course distinct from
The audio oscillators) never run the lpg. A semi annoying but tiny bit of code to do that in 2.2

**Comment by ContemporaryInsanity** [comment]
Same with particle noise.

**Comment by baconpaul** [comment]
The noise ones are harder. As far as I can see there’s no way to give the mutable engine a stable seed so repaints paint different noise curves. Same user experience but different cause.

the lpg one is an easier fix for sure
