### ISSUE TITLE
LFOxEG Waveform Display of LFO Only

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#847]
Maybe just another display issue that doesn't affect performance - but....

I'm using LFOxEG to add a low amplitude sawtooth LFO only to mix with a SSLFO triangle to add some jitter as it sweeps through a wave file in a Voxglitch granulator. So far so good.
 
But what I noticed is that the sawtooth waveform won't display in LFOxEG unless I crank up the Sustain of the Envelope. It doesn't affect the waveform as seen in the Scope to the right of LFOxEG but I'm wondering why the Sustain is needed for an LFO only waveform?

https://user-images.githubusercontent.com/14888092/219940609-581fdd3c-b6f2-4eae-b846-78431b7dc367.mp4

**Comment by baconpaul** [comment]
The short answer is the display shows lfoxeg 

should it not?

**Comment by baconpaul** [comment]
I suppose what I should do is always show lfo x eg and eg but if you connect the lfo only show a ghosted lfo also. That’s kinda what we do for rate freeze and amplitude in the vst so let me add it here too
