### ISSUE TITLE
I'm afraid EGxVCA Pan is borked

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-rack#849]
...but differently from Surge proper (I think). 

To hear it clearly: 
Bring up a Classic VCO
patch left to a LPF and right to a HPF, turn up the resonance
Patch those into EGxVCA L/R
Bring pan all the way left

The right speaker goes to silence, but you can hear the right side signal blended in with the left which is wrong. Messing with the other side filter makes it obvious.

**Comment by baconpaul** [comment]
As mentioned on discord 

https://github.com/surge-synthesizer/sst-basic-blocks/blob/9c6f15c1c42599a6f5913ba94963676f94c845f0/include/sst/basic-blocks/dsp/PanLaws.h#L56

I just copied this law from mixmaster and can easily add the other options it has

**Comment by baconpaul** [comment]
```
                                        else if (stereoPanMode == 1) {
                                                // Stereo balance equal power (+3dB), same as mono Equal power
                                                sinCosSqrt2(&panMatrix[1], &panMatrix[0], pan * float(M_PI_2));
                                        }
```
