### ISSUE TITLE
MIXER - not keeping settings

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#852]
If I set all Mixer channels to Mute and save the patch, the next time I start Rack with that patch, inputs 1, 2 and 3 are unmuted. The plugin is ignoring saved changed.  

![image](https://user-images.githubusercontent.com/14888092/220301307-acf06a24-38be-41f0-9a23-59e3a05449ab.png)

**Comment by Andreya-Autumn** [comment]
Hmm, I can't replicate this one here. What platform are you on, and what version of VCV and the Surge modules?

**Comment by baconpaul** [comment]
I wonder if it is the “first connect unmutes” interacting with saved state.
maybe try two mixers in a save one with inputs connected and one without?

**Comment by baconpaul** [comment]
OK I've confirmed this is indeed the "first hookup of input 2 unmutes" - which is the right behavior when you pull out the module - triggering when upstreaming. It unstreams muted then detects that first connection once the graph is built. 

I think what I need to do is in the event you are unstreamed, make it so you don't have the 'first hookup to unmute' behavior and only do that for new instances. But that's a bit annoying. Requires some thought.

Thanks for the bug report @therealkitman - it's been really great having you help us pin down these details.

**Comment by baconpaul** [comment]
This should be fixed in a nightly later tonight.
