### ISSUE TITLE
Couple LFOxEG nitpicks

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-rack#857]
In step seq type, "phase" becomes "shuffle" on the tooltip, but not on the faceplate. Was meant to change on both, no? 

Also on step seq type, the two deform types are behaving identically for me, both in rack and Surge proper actually. Are they really meant to be there?

**Comment by baconpaul** [comment]
Deform type 1 and 2 are subtly different for deform > 0 but the same for deform < 0. This is true in both surge and surge rack so no bug there.
