### ISSUE TITLE
EGxVCA Odd Gate Behaviour.

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#872]
Hi (again). I opened VCVRack which loaded my test patch for SurgeXT  plugins. I immediately realized it sounded wrong. Even though I had a single gate control at startup when I turned the gate trigger off/on I now had 4 gates in operation.

Does EGxVCA use 1 gate but normalize to other gates depending on how many LEFT/RIGHT input channels there are? If not then my patch was working for the wrong reasons since I should have had 4 gates for the 4 note input chord.

https://user-images.githubusercontent.com/14888092/223397590-081a1e46-5d83-4e8c-bf6e-35ce74a62b91.mp4

**Comment by baconpaul** [comment]
Between 2.1.1 and 2.1.3 we changed egxvca to normalize mono gates to poly signals so a patch made with 2.1.0 would indeed change. 

The changelog < https://github.com/surge-synthesizer/surge-rack/blob/main/docs/changelog.md> is pretty accurate - does that explain the issue here?

**Comment by therealkitman** [comment]
> does that explain the issue here?

Indeed it does. Sorry about that.

**Comment by baconpaul** [comment]
No need to apologize!
