### ISSUE TITLE
EGxVCA - Odd Gates Part 2

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#874]
This is basically a follow on from issue #872 (ignore the audio in this mp4 - not part of the problem)
I was experimenting with the mono/poly inputs mentioned in #872. I hooked up an EGxVCA with 3 poly input channels but 1 mono gate input. So far, so good.

But what I saw as odd was that if I close the patch then re-open  only 1 gate is active until the LFO starts a new cycle then all 3 ADSR channels - and outputs as shown on the oscilloscope - are active.

Not a show stopper but is it a similar issue as the Mixer issues #852 ?  

https://user-images.githubusercontent.com/14888092/223625800-b4f86772-2328-442d-99d9-c7725267fa5c.mp4

**Comment by baconpaul** [comment]
sorry to have missed this when it was opened. I just tagged it into our 2.2. milestone for this fall.

**Comment by baconpaul** [comment]
Funnily the cause of this bug isn't in your video :) but I was able to reproduce it

A monophonic gate and a polyphonic signal chooses the poly level out of order is roughly the problem.

Here's a network which shows it at startup. 

Looking at code now.

![Screenshot 2023-11-29 at 12 58 51 PM](https://github.com/surge-synthesizer/surge-rack/assets/13387561/3a7588c6-250e-4c23-bc84-96a20a04a8a4)
