### ISSUE TITLE
Quad LFO crashes when Randomized with STRIP

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge-rack#876]
Attempting to randomise QUAD LFO using Stoermelder STRIP consistently crashes rack.  Same with my similar unreleased randomisation module.

**Comment by baconpaul** [comment]
Thanks

No crash when I hold down Apple-R at head. Will look for 2.1.5

**Comment by baconpaul** [comment]
but immediate crash when randomizing with strip also.

**Comment by baconpaul** [comment]
yeah the stack is entirely in Strip. I'll look but this amounts to 'debug strip' it seems as much as anything else.

**Comment by ContemporaryInsanity** [comment]
Interesting.  As stated my RAND> module also crashes it, yet both are fine on all other modules I've tested so far, only QLFO fails.

**Comment by baconpaul** [comment]
yeah i wonder what you are doing that randomize isn't that quadlfo tickles, and which of those 3 things has the bug :)

**Comment by ContemporaryInsanity** [comment]
My immediate reaction was to choose a similar module to try, so QUAD AD it was, which works as expected, so perhaps there may be a subtle difference between QUAD LFO & QUAD AD that causes this?

**Comment by baconpaul** [comment]
The bug is Strip is assuming that given a ParamWidget* that ParamWidget->getParamQuantity is not null and it doesn't check it.

The QUadLFO has a case where it is

I can probably change  QuadLFO but there's no requirement that a widget always has a quantity so strip and other clients should also add a null check.

**Comment by baconpaul** [comment]
Next nightly will be fixed

I still think strip should check nulls though!

**Comment by ContemporaryInsanity** [comment]
Top work!

I'll fix mine too, thanks.
