### ISSUE TITLE
Modern VCO v. 2.1.4.0: Preset with "Multi:Sine" selected loads as "Multi:Square"

### ISSUE THREAD

**Issue by thelarchmage** [surge-synthesizer/surge-rack#879]
When I attempted to save a preset for Modern VCO with the "Multi: Sine" option selected in the context menu, the preset always loads with "Multi: Square" selected instead. 
![ModernVCOSuperSineSave](https://user-images.githubusercontent.com/47726871/226204897-8c12eb7e-7b2a-4290-9ff6-21d7f26ab52f.JPG)
![ModernVCOSuperSineLoad](https://user-images.githubusercontent.com/47726871/226204899-12709abf-0f20-4c42-a2c6-ef07ad19d071.JPG)

**Comment by baconpaul** [comment]
oooh that's not awesome. can you attach the user preset your re using here?

**Comment by baconpaul** [comment]
oh wow you don't need a preset. This also happens if you just save and restore a patch with multi sine.

Looking.

**Comment by baconpaul** [comment]
oh damnit i see it. simple typo.

Pushing a fix now. Will be in next nightly and in 2.1.5 when we get our next release together. I may do a quick 2.1.5 just for this before my vaca though. That's a bad bug.

**Comment by baconpaul** [comment]
OK this (and two other small fixes) I put together and pushed to a library 2.1.5.0

so grab the nightly in about 20 minutes or wait a few days for the library to churn and should be all fixed.

Sorry bout that - thanks for the report!

**Comment by thelarchmage** [comment]
Hooray! That was *fast*! I can definitely wait until Library does its thing. Working on a long-term project.

**Comment by baconpaul** [comment]
Great!
