### ISSUE TITLE
Excluding engine mode in Twist VCO randomization

### ISSUE THREAD

**Issue by firolightfog** [surge-synthesizer/surge-rack#882]
Dear Paul,

With reference to this [VCV Forum topic](https://community.vcvrack.com/t/question-on-surge-twist-randomization/19600/3), would you please consider limiting the standard VCV module randomization (Ctrl-R) to the knobs only and leave the "engine" unchanged?

A potential implementation would be adding an option in the context menu for exclusion. Similarly as we see it in Vult Trummor2:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/34127628/226595722-86f5b343-55fa-43ed-998f-691619146776.png">

Best regards, Andras

**Comment by baconpaul** [comment]
Perfect that’s what I had planned yes.

**Comment by baconpaul** [comment]
Oh this is a dup of #884 which I just put in a PR to close. Should be in nightly soon and release a bit less soon.
