### ISSUE TITLE
[FEATURE] - WaveShaper mode plot

### ISSUE THREAD

**Issue by DerozerDSP** [surge-synthesizer/surge-rack#883]
Hi,

is there any way on WaveShaper to see the shape plot as -1/1 (input) to -1/1 (output) mapping instead of sine (as input) to -1/1 (output)?

Usually on WaveShaper thats the way it visualize the input/output (Fruity WaveShaper for example, or Trasher2 and so on).

Not sure how thats mapping is named, but any way to display it “classic way”?

Thanks

**Comment by DerozerDSP** [comment]
@baconpaul I'd like to keep both previews, maybe with a mode/switch? Using the right/click module panel, or directly on the plot.

**Comment by baconpaul** [comment]
Yeah I was thinking I could make it like 2d/3d in wavetable osc 

Heck can even show response curve, impact on sin and impact on saw as 3 choices when I get to it

**Comment by DerozerDSP** [comment]
Hi, 

any ETA for this feature? :)

Thanks

**Comment by baconpaul** [comment]
Nope. If you are a dev I’m happy to give you notes on how to add it. But no eta from me

**Comment by baconpaul** [comment]
<img width="336" alt="Screen Shot 2023-05-20 at 9 22 05 PM" src="https://github.com/surge-synthesizer/surge-rack/assets/13387561/97bb9c70-5862-4960-b356-a920985f9f5a">
<img width="358" alt="Screen Shot 2023-05-20 at 9 22 15 PM" src="https://github.com/surge-synthesizer/surge-rack/assets/13387561/c63ea644-6755-4e9c-806f-86fd08c6817e">

I dunno. WDYT?

**Comment by baconpaul** [comment]
![In Action](https://github.com/surge-synthesizer/surge-rack/assets/13387561/2776c169-d18b-49cf-af32-1f94448f1eb7)

There you go. I'll merge that tonight and see what folks think in the nightly.

**Comment by baconpaul** [comment]
OK this is going to be in the 2.1.6 release which I just submitted to the library. Thanks for the suggestion.

**Comment by DerozerDSP** [comment]
@baconpaul thanks for the fix! Finally I was able to check it out :) Just a question: is it normal that (with 3 instances of WaveShaper), if I change the setting in one instance, it changes in every instances opened?

**Comment by baconpaul** [comment]
Yeah it’s a global setting. Was easier

some of the wave shapers act like octave dividers and doublers so I was thinking 2 cycles can show that. It’s just a choice though nothing more fundamental

**Comment by DerozerDSP** [comment]
@baconpaul probably I miss the point: which preset/shape on the module has first cycle different rather than second?

**Comment by Andreya-Autumn** [comment]
None of them divide as far as I know. Several of them multiply though, a pure sine into any of the "Harmonic" ones would be the most obvious example of that. 

I always thought it looked subjectively good with the two cycles. But with the transform/response graph showing it feels a little more squished. Maybe we could try 1 cycle in that mode Paul, wdyt?

**Comment by baconpaul** [comment]
Sure

**Comment by baconpaul** [comment]
OK the next nightly and the 2.2 module release (this fall) will switch to a single cycle in wave + transform mode.

**Comment by DerozerDSP** [comment]
Nice, thanks! I'll try when released :)

Not sure though what @baconpaul meant with "dividers" on wave shaper; Is that really possible or just and error on the message?

**Comment by baconpaul** [comment]
I had thought incorrectly that I used the state to make a flip flop divider as one of our waveshapers but I’ve only thought about thst not coded it
