### ISSUE TITLE
Limited randomization on Surge Twist

### ISSUE THREAD

**Issue by firolightfog** [surge-synthesizer/surge-rack#884]
![image](https://github.com/surge-synthesizer/surge-rack/assets/34127628/edaf6023-f25f-4512-9704-be5b19251e50)

With reference to this forum [topic](https://community.vcvrack.com/t/question-on-surge-twist-randomization/19600/2) could you please consider exclude the engine randomization in case of Surge Twist?

A context-menu option (like in Vult Trummor 2) may work well.

Best regards, Andras

**Comment by baconpaul** [comment]
Oh thanks! And sure

**Comment by baconpaul** [comment]
next nightly should have this. will try and get it to the library next couple of weeks. one or two other things to do along the way

**Comment by firolightfog** [comment]
Eh, sorry for the duplication! 
Many thanks for the feature!

**Comment by firolightfog** [comment]
You are incredible!
