### ISSUE TITLE
Start of Envelope Stage menu option for EG x VCA

### ISSUE THREAD

**Issue by imDanSable** [surge-synthesizer/surge-rack#890]
I think it would be a nice feature if the menu allowed switching the EOC port to a SOA port (start of attack stage).
This would be enough for me personally, but the idea could be further generalized to extend to:

Start of Attack
Start of Decay
Start of Sustain
Start of Hold
Start of Release
End of Cycle

What do you think?

**Comment by baconpaul** [comment]
Oh good idea. Our next major version of these will probably come at end of summer so let me tag this idea into that milestone

**Comment by baconpaul** [comment]
This will be in the next nightly and will be included in Surge 2.2 later this fall. Thanks!
