### ISSUE TITLE
Mixer mute/solo tooltips wrong

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-rack#900]
The tooltips on the mutes read "input 9-14" and the solos read "input 15-20".

**Comment by Andreya-Autumn** [comment]
It was user brkl on Discord who reported it. :) And btw, the noise and ring mod level dials have the same problem also.

**Comment by baconpaul** [comment]
Ha well it was just all wrong! PR in fixing it now.
