### ISSUE TITLE
GUI: ADSR pots (the time based controls of ADR) seem to "stick" at .004 briefly 

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge-rack#93]
![Label_Update](https://user-images.githubusercontent.com/11078351/57263046-c8252a80-7034-11e9-9771-4f1ca535a885.gif)

The .gif sums it up but when dragging the time related controls to the left bounds of the pot the value in the GUI seems to "stick" at .004 briefly before hitting .000

**Comment by baconpaul** [comment]
The reason for this jump it seems is that the ct_envtime in Parameter.cpp converts the float to time using pow(2.0, f). The range is -8 to 5.  But when you hit exactly -8 it hardcodes to 0.000 s. From Parameter.cpp

```
            else if (f == val_min.f)
            {
               sprintf(txt, "0.000 s");
            }
            else
            {
               sprintf(txt, "%.3f s", powf(2.0f, val.f));
            }
```

So 2^-8 = 0.00390625 Which means 2^-7.99999 looks like 0.004 at 3 decimals. Hence the jump. The internal parameter is formatting that way on purpose.

I don't think there's anything to do here. Surge proper does the same. It's a bit odd but just kinda how things are set up. So I'm going to close this unless you object?
