### ISSUE TITLE
Old module presets bundled in plugin folder, crash on load.

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-rack#933]
So, user presets save in appropriate folders in ~/documents/rack2/presets. And the XT modules which have internal factory presets load those correctly by default. 

But there is an additional folder with presets being installed with the XT plugins. *Not* in rack2/presets, but in rack2/plugins/SurgeXTrack/presets. 

You really gotta go out of your way to attempt loading those. Lots of folder nav in the rack preset mechanism etc. But if you do that rack crashes: 
[ModulePresetCrash.txt](https://github.com/surge-synthesizer/surge-rack/files/12563823/ModulePresetCrash.txt)

**Comment by Andreya-Autumn** [comment]
Thanks Peter for finding this one. It makes sense no one did until now. Looks like the issue is in fact as simple as this: We're still shipping 4 year old patches with the new modules. :P See last commit date here. 
https://github.com/surge-synthesizer/surge-rack/tree/main/presets

**Comment by Andreya-Autumn** [comment]
If my sassumption is correct, the fix here is just to not ship those. In which case the above PR will achieve that. @baconpaul will have to confirm that I'm not being overzealous.

**Comment by Petervos2018** [comment]
Do do indeed load in V1 and it was the "that's not what leslie wanted" preset that made me curious 😉 

![afbeelding](https://github.com/surge-synthesizer/surge-rack/assets/46076474/505d7813-2141-4a69-a85b-f6571f8f4523)

**Comment by Andreya-Autumn** [comment]
Makes sense! Next XT module version will not come with these particular footguns. (Except the code quality checks on that PR failed for some reason, but we'll work it out). Thanks again for flagging!

**Comment by Andreya-Autumn** [comment]
Fixed in #934
