### ISSUE TITLE
MIDI Program Change

### ISSUE THREAD

**Issue by mkohlhaas** [surge-synthesizer/surge-rack#936]
Just a quick question: Is there a way to send MiDi program change messages?

Thanks for everything you do!

Best regards!

**Comment by baconpaul** [comment]
to the surge vcv rack modules? no. what would that even do? but I don' think the rack midi devices even consume the message.

if you mean to the surge vst, the answer is "yes; but not with the vst3, and only in the nightly" - we have added it in our development version.

**Comment by baconpaul** [comment]
so you mean like in the rack delay module you can swap the presets?

the thing about rack is I don't really get access to the raw midi stream. (You can but it is quite a bit of work and very specialized) so I don't get those messages.

If you have a way to generate rack param change events I suppose I could listen to them and then something like the mixmaster automation thing could work perhaps? Right now those presets are also not exposed as params but having a non-ported input you could trigger to maybe?
