### ISSUE TITLE
ED x VCA panel display portion

### ISSUE THREAD

**Issue by firolightfog** [surge-synthesizer/surge-rack#941]
I am aware that changing the UI is always painful. But knowing that I at least raised this issue makes me feel better. So my apologies in advance... 

Would you please consider changing the size of the double screen in EGxVCA? Any of the green lines would be a logical and pleasant weight. But the currently used portion (see red line) is completely messed up. 

<img width="242" alt="image" src="https://github.com/surge-synthesizer/surge-rack/assets/34127628/dca4f1a6-d9f9-40ea-9cbe-1745ed2c19d9">

**Comment by baconpaul** [comment]
Oh ha yeah that’s an easy change. The position was arbitrary and until I saw your weight lines I didn’t see it ws misaligned so badly to the knobs

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge-rack/blob/44221739a65c0ceb29b88a17ddf44737f76c75b5/src/EGxVCA.cpp#L597

It’s just turning the 65/35 there into a local var and tweaking it

**Comment by baconpaul** [comment]
next nightly should have this resolved. thanks for flagging
