### ISSUE TITLE
CXOR randomize

### ISSUE THREAD

**Issue by firolightfog** [surge-synthesizer/surge-rack#967]
A minor glitch is that Ctrl-R sometimes selects _empty_ mode in CXOR. (Obviously it's not the way we use this module but anyway ....)

<img width="608" alt="image" src="https://github.com/surge-synthesizer/surge-rack/assets/34127628/de528b13-65af-40f6-9812-1a96c7895b44">

**Comment by baconpaul** [comment]
Ahh cool. I’m sure once 22 finally hits the library we will have to do a cleanup install. I’ll add this to that set
