### ISSUE TITLE
Rack closing when I attempt to use VCO modules

### ISSUE THREAD

**Issue by technochitlin** [surge-synthesizer/surge-rack#969]
I was building a patch, and noticed that I was still using an older beta of SurgeXT Rack. I deleted the SurgeXT folder from my Rack installation, let Rack download the latest install file, and now when I try to load any of the FM modules Rack immediately exits. Did I do this wrong? I've never had any problem with any of your modules before so I suspect user error; I just don't know how to proceed.

Windows 10 Pro up-to-date
VCV Rack ver. 2.4.1

**Comment by Petervos2018** [comment]
https://community.vcvrack.com/t/surge-rack-sporadic-crashes-after-installing-vst-1-3/21156?u=yeager

**Comment by baconpaul** [comment]
Yeah and this should be in the library this week. Been stalled for a few but I’ve chatted with the team

**Comment by technochitlin** [comment]
Hah! Found that forum post a little while ago and downloaded from here- problem fixed! Thanks!

**Comment by baconpaul** [comment]
Great
