### ISSUE TITLE
Understanding unsupported 32bit builds rationale

### ISSUE THREAD

**Issue by falkTX** [surge-synthesizer/surge-rack#975]
While updating surge-rack for cardinal I have quite a few CI builds failing because non-windows 32bit builds now trigger an error.
I read the comment but dont fully understand, spring reverb is broken in 32bit? Why is that exactly?

note that 32bit is not just for old linux systems, web assembly uses it and X32 mode in 64bit linux systems is a thing too https://en.wikipedia.org/wiki/X32_ABI
there is also the usecase of 64bit kernels running a 32bit userspace, which is quite handy for small ARM/embed platforms

**Comment by baconpaul** [comment]
It is unsupported mostly because it doesn’t work and no one has debugged it.

**Comment by baconpaul** [comment]
The only change here was we failed the cmake earlier and more vocally. I wonder if you just went to not do that. Did you have a working 32 but build of spring reverb in your env? If so maybe just kill the cmake warn

**Comment by baconpaul** [comment]
(Kill it optionally of course. A straight rpi gcc 32 but build of surge doesn't work hence the early bailout. If you want to add a var to skip the fatal error etc.... is what I meant)

**Comment by falkTX** [comment]
I was not aware it was broken in the first place.
You can see it working here on a quick test patch https://cardinal.kx.studio/live?patchurl=https://kx.studio/Paste/raw/4AlxI

I dont know the module that well, do you spot anything that is broken?

**Comment by baconpaul** [comment]
It won’t even build on a standard raspbian 32 bit in the mainline surge build

lookalike that fatal error should get downgraded on rack builds optionally

**Comment by falkTX** [comment]
> It won’t even build on a standard raspbian 32 bit in the mainline surge build

what is the error? related to bundling files with the binary?

anyhow I have been building 32bit cardinal with surge-rack since initially adding surge and have no reports of issues there, except for the oddities on web-assembly we discussed one time (some display operation triggers a crash, so we do not have the filters graph on wasm builds)

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/issues/6481

I can exempt rack from early stop in a week when I’m back from vaca
