### ISSUE TITLE
-fno-char8_t flag requires GCC >= 8

### ISSUE THREAD

**Issue by falkTX** [surge-synthesizer/surge-rack#976]
Latest surge-rack now uses `-fno-char8_t` which requires a new compiler.
Please make it optional as it breaks the build for platforms where the build was okay before.

As far as I can tell the flag was introduced in GCC 8.

**Comment by baconpaul** [comment]
Either I can remove it when back from vaca in a week or if you push a pr to remove it I can merge it btw

**Comment by baconpaul** [comment]
Pushed a change for both of the issues you raised

Within the next 6-12 months or so I bet we will move surge to C++20. Rack is on gcc-12 and libc2.31 so it should work. Just a heads up that when that happens we will drop support for gcc versions older than probably 11 or so.

**Comment by falkTX** [comment]
understood, thanks for the heads up and thanks for the fixes.

please mention the topic again on the last release before such a change happens. that would allow to prepare in advance. either keeping an old version or figure out some way to update compilers/toolchain

**Comment by baconpaul** [comment]
Yeah it will be a major release and in the changelog and communicated ahead indeed. Nothing imminent.
