### ISSUE TITLE
Missing face markings in VST VCV2 plugin versions.

### ISSUE THREAD

**Issue by Mr-MG** [surge-synthesizer/surge-rack#991]
Greetings,

My apologies if this is a re-post. I looked but didn't see this issue.

Upon re-opening a project using the Surge Wavetable Oscillator via VST3 (or VST2, I've tried both) plugin of VCV Rack 2 (ver 2.4.1) (Windows 10 64 bit system) all the face markings are missing. Attempting to add a fresh version of the oscillator shows all Surge XT modules to be missing face markings. The module still works in terms of manipulating sound but no indicators or labels are present. I checked this in both Reaper and BitWig Studio (most recent versions) and found it happens in both programs.

This does not happen in the stand-alone version of VCV2, only in the VST plugin versions of VCV2.

![Surge Faceoff](https://github.com/surge-synthesizer/surge-rack/assets/59236467/b449438a-6fb1-47c4-8051-d1b7abdb802f)

**Comment by baconpaul** [comment]
Wow there’s a font error which can do that but u thought we were doing the right thing. Let me look on my Mac tomorrow

**Comment by baconpaul** [comment]
hmm ok my mac doesn't do this with the 2.4.1 vst3 in reaper.
let me ask some of my windows colleagues to reproduce.

**Comment by baconpaul** [comment]
One other thing @Mr-MG - can you wedge the ui like this reliably? if so can you do so then send me the log.txt from your Documents/Rack2 directory for that session? You can just zip it and attach it here. Thanks!

**Comment by Mr-MG** [comment]
Thanks for looking into this.  You mentioned this may be a font issue. Is
it possible it's a conflict with a font on my system?

I think I also have the pre-release version of Surge installed. If I do I
will remove it and see if that has any effect. When  I get home from work
today I'll check.

Thanks again for your help.

**Comment by Mr-MG** [comment]
Just saw your response. As soon as I get home from my first shift this
morning I'll run it and send the file. Thanks!

**Comment by baconpaul** [comment]
Ahh right depending on how old that pre-release is that may also cause it. Some of the very older versions did indeed have this bug and I fixed them. (Basically the lifetime of a font in pro is different than in standalone and theres an API you use to work in both). Also the latest has bunches of new things too.  You can always let us know the version from the info in the right mouse menu - the latest in the library is 2.2.2.0

**Comment by Mr-MG** [comment]
Well, my apologies. After deleting all pre-release and Surge XT files and then re-adding Surge XT to my VCV2 library the missing font problem appears to have been remedied - something I should have done initially before bothering you with the issue.

I've reopened the files I was working on in Reaper (and tested it in Bitwig) and both are showing properly. I'm closing this, and again my apologies.

**Comment by baconpaul** [comment]
Oh great! I checked right away because I was sure I had fixed it and it’s a real bug! Luckily had :)

enjoy making music with surge! Have fun!

**Comment by Mr-MG** [comment]
Thanks! I appreciate it.

Love the Surge XT modules, they actually pull me away from my hardware
synths!

Cheers!
