### ISSUE TITLE
Issue with v1.

### ISSUE THREAD

**Issue by TheGuyWhoo** [surge-synthesizer/surge-rack#998]
My gpu is old so I can only use v1. When I try to build it on win 10 for vcv rack 1.1.6, with sdk 1.1.6, I get this error:

        surge/src/common/Parameter.cpp:774:24: error: 'numeric_limits' is not a member of 'std'
          774 |       val_min.i = std::numeric_limits<int>::min();
              |                        ^~~~~~~~~~~~~~
        surge/src/common/Parameter.cpp:774:39: error: expected primary-expression before 'int'
          774 |       val_min.i = std::numeric_limits<int>::min();
              |                                       ^~~
        surge/src/common/Parameter.cpp:775:24: error: 'numeric_limits' is not a member of 'std'
          775 |       val_max.i = std::numeric_limits<int>::max();
              |                        ^~~~~~~~~~~~~~
        surge/src/common/Parameter.cpp:775:39: error: expected primary-expression before 'int'
          775 |       val_max.i = std::numeric_limits<int>::max();

Hope you will help even though v1 is old news.

**Comment by TheGuyWhoo** [comment]
nevermind, parameter.cpp needs #include <limits>

**Comment by TheGuyWhoo** [comment]
Fails to load with this message

    [34.302 warn src/plugin.cpp:158] Could not load plugin C:\Users\nick\DOCUME~1/Rack/plugins-v1/SurgeRack: Failed to load library C:\Users\nick\DOCUME~1/Rack/plugins-v1/SurgeRack/plugin.dll: code 127

**Comment by baconpaul** [comment]
The makefile I think adds an Ilimits but not sure 

which hash are you checking out?

honestly don’t really have capacity or environment to debug rack 1 on windows 10. But doesn’t rack 1 still have a working binary in the library?

**Comment by TheGuyWhoo** [comment]
I checked out branch v1_final. Unfortunately for whatever reason it doesn't still have binaries for v1. Maybe you do?

**Comment by baconpaul** [comment]
I don’t - I wonder if I cleaned them out when v2 shipped and we moved to xt 

can you still subscribe in the rack library?

**Comment by TheGuyWhoo** [comment]
Yes I can

**Comment by Petervos2018** [comment]
> Yes I can

![afbeelding](https://github.com/surge-synthesizer/surge-rack/assets/46076474/7516b826-0fa2-4b71-8a72-52e1ca9e52d8)

Then you should be offered/able to download a compiled version via Rack, or am I missing the point.
Do you want to compile it yourself ?

**Comment by TheGuyWhoo** [comment]
You likely have a binary from before it was taken out of the library. The problem is that when I build it rack refuses to load the plugin with error code 127, as I said.

**Comment by TheGuyWhoo** [comment]
Would you mind sharing you binary here please?

**Comment by TheGuyWhoo** [comment]
Absolute legend, that works! Thanks man.

**Comment by baconpaul** [comment]
OK great. Closing this. Thanks for the help @Petervos2018 

still not entirely sure why its not in the library but glad its solved!
